// Code generated by ent, DO NOT EDIT.

package instance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/KHU-RETURN/rcp-server/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldID, id))
}

// OpenstackID applies equality check predicate on the "openstack_id" field. It's identical to OpenstackIDEQ.
func OpenstackID(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldOpenstackID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldName, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldStatus, v))
}

// ImageID applies equality check predicate on the "image_id" field. It's identical to ImageIDEQ.
func ImageID(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldImageID, v))
}

// FlavorID applies equality check predicate on the "flavor_id" field. It's identical to FlavorIDEQ.
func FlavorID(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldFlavorID, v))
}

// KeyName applies equality check predicate on the "key_name" field. It's identical to KeyNameEQ.
func KeyName(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldKeyName, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldNote, v))
}

// ProviderCreatedAt applies equality check predicate on the "provider_created_at" field. It's identical to ProviderCreatedAtEQ.
func ProviderCreatedAt(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldProviderCreatedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldUpdatedAt, v))
}

// OpenstackIDEQ applies the EQ predicate on the "openstack_id" field.
func OpenstackIDEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldOpenstackID, v))
}

// OpenstackIDNEQ applies the NEQ predicate on the "openstack_id" field.
func OpenstackIDNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldOpenstackID, v))
}

// OpenstackIDIn applies the In predicate on the "openstack_id" field.
func OpenstackIDIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldOpenstackID, vs...))
}

// OpenstackIDNotIn applies the NotIn predicate on the "openstack_id" field.
func OpenstackIDNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldOpenstackID, vs...))
}

// OpenstackIDGT applies the GT predicate on the "openstack_id" field.
func OpenstackIDGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldOpenstackID, v))
}

// OpenstackIDGTE applies the GTE predicate on the "openstack_id" field.
func OpenstackIDGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldOpenstackID, v))
}

// OpenstackIDLT applies the LT predicate on the "openstack_id" field.
func OpenstackIDLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldOpenstackID, v))
}

// OpenstackIDLTE applies the LTE predicate on the "openstack_id" field.
func OpenstackIDLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldOpenstackID, v))
}

// OpenstackIDContains applies the Contains predicate on the "openstack_id" field.
func OpenstackIDContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldOpenstackID, v))
}

// OpenstackIDHasPrefix applies the HasPrefix predicate on the "openstack_id" field.
func OpenstackIDHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldOpenstackID, v))
}

// OpenstackIDHasSuffix applies the HasSuffix predicate on the "openstack_id" field.
func OpenstackIDHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldOpenstackID, v))
}

// OpenstackIDEqualFold applies the EqualFold predicate on the "openstack_id" field.
func OpenstackIDEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldOpenstackID, v))
}

// OpenstackIDContainsFold applies the ContainsFold predicate on the "openstack_id" field.
func OpenstackIDContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldOpenstackID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldName, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldStatus, v))
}

// ImageIDEQ applies the EQ predicate on the "image_id" field.
func ImageIDEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldImageID, v))
}

// ImageIDNEQ applies the NEQ predicate on the "image_id" field.
func ImageIDNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldImageID, v))
}

// ImageIDIn applies the In predicate on the "image_id" field.
func ImageIDIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldImageID, vs...))
}

// ImageIDNotIn applies the NotIn predicate on the "image_id" field.
func ImageIDNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldImageID, vs...))
}

// ImageIDGT applies the GT predicate on the "image_id" field.
func ImageIDGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldImageID, v))
}

// ImageIDGTE applies the GTE predicate on the "image_id" field.
func ImageIDGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldImageID, v))
}

// ImageIDLT applies the LT predicate on the "image_id" field.
func ImageIDLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldImageID, v))
}

// ImageIDLTE applies the LTE predicate on the "image_id" field.
func ImageIDLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldImageID, v))
}

// ImageIDContains applies the Contains predicate on the "image_id" field.
func ImageIDContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldImageID, v))
}

// ImageIDHasPrefix applies the HasPrefix predicate on the "image_id" field.
func ImageIDHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldImageID, v))
}

// ImageIDHasSuffix applies the HasSuffix predicate on the "image_id" field.
func ImageIDHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldImageID, v))
}

// ImageIDEqualFold applies the EqualFold predicate on the "image_id" field.
func ImageIDEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldImageID, v))
}

// ImageIDContainsFold applies the ContainsFold predicate on the "image_id" field.
func ImageIDContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldImageID, v))
}

// FlavorIDEQ applies the EQ predicate on the "flavor_id" field.
func FlavorIDEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldFlavorID, v))
}

// FlavorIDNEQ applies the NEQ predicate on the "flavor_id" field.
func FlavorIDNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldFlavorID, v))
}

// FlavorIDIn applies the In predicate on the "flavor_id" field.
func FlavorIDIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldFlavorID, vs...))
}

// FlavorIDNotIn applies the NotIn predicate on the "flavor_id" field.
func FlavorIDNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldFlavorID, vs...))
}

// FlavorIDGT applies the GT predicate on the "flavor_id" field.
func FlavorIDGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldFlavorID, v))
}

// FlavorIDGTE applies the GTE predicate on the "flavor_id" field.
func FlavorIDGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldFlavorID, v))
}

// FlavorIDLT applies the LT predicate on the "flavor_id" field.
func FlavorIDLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldFlavorID, v))
}

// FlavorIDLTE applies the LTE predicate on the "flavor_id" field.
func FlavorIDLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldFlavorID, v))
}

// FlavorIDContains applies the Contains predicate on the "flavor_id" field.
func FlavorIDContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldFlavorID, v))
}

// FlavorIDHasPrefix applies the HasPrefix predicate on the "flavor_id" field.
func FlavorIDHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldFlavorID, v))
}

// FlavorIDHasSuffix applies the HasSuffix predicate on the "flavor_id" field.
func FlavorIDHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldFlavorID, v))
}

// FlavorIDEqualFold applies the EqualFold predicate on the "flavor_id" field.
func FlavorIDEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldFlavorID, v))
}

// FlavorIDContainsFold applies the ContainsFold predicate on the "flavor_id" field.
func FlavorIDContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldFlavorID, v))
}

// KeyNameEQ applies the EQ predicate on the "key_name" field.
func KeyNameEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldKeyName, v))
}

// KeyNameNEQ applies the NEQ predicate on the "key_name" field.
func KeyNameNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldKeyName, v))
}

// KeyNameIn applies the In predicate on the "key_name" field.
func KeyNameIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldKeyName, vs...))
}

// KeyNameNotIn applies the NotIn predicate on the "key_name" field.
func KeyNameNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldKeyName, vs...))
}

// KeyNameGT applies the GT predicate on the "key_name" field.
func KeyNameGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldKeyName, v))
}

// KeyNameGTE applies the GTE predicate on the "key_name" field.
func KeyNameGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldKeyName, v))
}

// KeyNameLT applies the LT predicate on the "key_name" field.
func KeyNameLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldKeyName, v))
}

// KeyNameLTE applies the LTE predicate on the "key_name" field.
func KeyNameLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldKeyName, v))
}

// KeyNameContains applies the Contains predicate on the "key_name" field.
func KeyNameContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldKeyName, v))
}

// KeyNameHasPrefix applies the HasPrefix predicate on the "key_name" field.
func KeyNameHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldKeyName, v))
}

// KeyNameHasSuffix applies the HasSuffix predicate on the "key_name" field.
func KeyNameHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldKeyName, v))
}

// KeyNameEqualFold applies the EqualFold predicate on the "key_name" field.
func KeyNameEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldKeyName, v))
}

// KeyNameContainsFold applies the ContainsFold predicate on the "key_name" field.
func KeyNameContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldKeyName, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldNote, v))
}

// ProviderCreatedAtEQ applies the EQ predicate on the "provider_created_at" field.
func ProviderCreatedAtEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldProviderCreatedAt, v))
}

// ProviderCreatedAtNEQ applies the NEQ predicate on the "provider_created_at" field.
func ProviderCreatedAtNEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldProviderCreatedAt, v))
}

// ProviderCreatedAtIn applies the In predicate on the "provider_created_at" field.
func ProviderCreatedAtIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldProviderCreatedAt, vs...))
}

// ProviderCreatedAtNotIn applies the NotIn predicate on the "provider_created_at" field.
func ProviderCreatedAtNotIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldProviderCreatedAt, vs...))
}

// ProviderCreatedAtGT applies the GT predicate on the "provider_created_at" field.
func ProviderCreatedAtGT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldProviderCreatedAt, v))
}

// ProviderCreatedAtGTE applies the GTE predicate on the "provider_created_at" field.
func ProviderCreatedAtGTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldProviderCreatedAt, v))
}

// ProviderCreatedAtLT applies the LT predicate on the "provider_created_at" field.
func ProviderCreatedAtLT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldProviderCreatedAt, v))
}

// ProviderCreatedAtLTE applies the LTE predicate on the "provider_created_at" field.
func ProviderCreatedAtLTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldProviderCreatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Instance {
	return predicate.Instance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Instance {
	return predicate.Instance(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKeypair applies the HasEdge predicate on the "keypair" edge.
func HasKeypair() predicate.Instance {
	return predicate.Instance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, KeypairTable, KeypairColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeypairWith applies the HasEdge predicate on the "keypair" edge with a given conditions (other predicates).
func HasKeypairWith(preds ...predicate.KeyPair) predicate.Instance {
	return predicate.Instance(func(s *sql.Selector) {
		step := newKeypairStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Instance) predicate.Instance {
	return predicate.Instance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Instance) predicate.Instance {
	return predicate.Instance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Instance) predicate.Instance {
	return predicate.Instance(sql.NotPredicates(p))
}
