// Code generated by ent, DO NOT EDIT.

package function

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/KHU-RETURN/rcp-server/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldName, v))
}

// Wasm applies equality check predicate on the "wasm" field. It's identical to WasmEQ.
func Wasm(v []byte) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldWasm, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldLanguage, v))
}

// DataMode applies equality check predicate on the "data_mode" field. It's identical to DataModeEQ.
func DataMode(v bool) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldDataMode, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v []byte) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldSource, v))
}

// KeyHash applies equality check predicate on the "key_hash" field. It's identical to KeyHashEQ.
func KeyHash(v []byte) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldKeyHash, v))
}

// KeyCreatedAt applies equality check predicate on the "key_created_at" field. It's identical to KeyCreatedAtEQ.
func KeyCreatedAt(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldKeyCreatedAt, v))
}

// KeyExpiresAt applies equality check predicate on the "key_expires_at" field. It's identical to KeyExpiresAtEQ.
func KeyExpiresAt(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldKeyExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Function {
	return predicate.Function(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Function {
	return predicate.Function(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Function {
	return predicate.Function(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Function {
	return predicate.Function(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Function {
	return predicate.Function(sql.FieldContainsFold(FieldName, v))
}

// WasmEQ applies the EQ predicate on the "wasm" field.
func WasmEQ(v []byte) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldWasm, v))
}

// WasmNEQ applies the NEQ predicate on the "wasm" field.
func WasmNEQ(v []byte) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldWasm, v))
}

// WasmIn applies the In predicate on the "wasm" field.
func WasmIn(vs ...[]byte) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldWasm, vs...))
}

// WasmNotIn applies the NotIn predicate on the "wasm" field.
func WasmNotIn(vs ...[]byte) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldWasm, vs...))
}

// WasmGT applies the GT predicate on the "wasm" field.
func WasmGT(v []byte) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldWasm, v))
}

// WasmGTE applies the GTE predicate on the "wasm" field.
func WasmGTE(v []byte) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldWasm, v))
}

// WasmLT applies the LT predicate on the "wasm" field.
func WasmLT(v []byte) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldWasm, v))
}

// WasmLTE applies the LTE predicate on the "wasm" field.
func WasmLTE(v []byte) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldWasm, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Function {
	return predicate.Function(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Function {
	return predicate.Function(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Function {
	return predicate.Function(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Function {
	return predicate.Function(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Function {
	return predicate.Function(sql.FieldContainsFold(FieldLanguage, v))
}

// DataModeEQ applies the EQ predicate on the "data_mode" field.
func DataModeEQ(v bool) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldDataMode, v))
}

// DataModeNEQ applies the NEQ predicate on the "data_mode" field.
func DataModeNEQ(v bool) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldDataMode, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v []byte) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v []byte) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...[]byte) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...[]byte) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v []byte) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v []byte) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v []byte) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v []byte) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldSource, v))
}

// SourceIsNil applies the IsNil predicate on the "source" field.
func SourceIsNil() predicate.Function {
	return predicate.Function(sql.FieldIsNull(FieldSource))
}

// SourceNotNil applies the NotNil predicate on the "source" field.
func SourceNotNil() predicate.Function {
	return predicate.Function(sql.FieldNotNull(FieldSource))
}

// KeyHashEQ applies the EQ predicate on the "key_hash" field.
func KeyHashEQ(v []byte) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldKeyHash, v))
}

// KeyHashNEQ applies the NEQ predicate on the "key_hash" field.
func KeyHashNEQ(v []byte) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldKeyHash, v))
}

// KeyHashIn applies the In predicate on the "key_hash" field.
func KeyHashIn(vs ...[]byte) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldKeyHash, vs...))
}

// KeyHashNotIn applies the NotIn predicate on the "key_hash" field.
func KeyHashNotIn(vs ...[]byte) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldKeyHash, vs...))
}

// KeyHashGT applies the GT predicate on the "key_hash" field.
func KeyHashGT(v []byte) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldKeyHash, v))
}

// KeyHashGTE applies the GTE predicate on the "key_hash" field.
func KeyHashGTE(v []byte) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldKeyHash, v))
}

// KeyHashLT applies the LT predicate on the "key_hash" field.
func KeyHashLT(v []byte) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldKeyHash, v))
}

// KeyHashLTE applies the LTE predicate on the "key_hash" field.
func KeyHashLTE(v []byte) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldKeyHash, v))
}

// KeyHashIsNil applies the IsNil predicate on the "key_hash" field.
func KeyHashIsNil() predicate.Function {
	return predicate.Function(sql.FieldIsNull(FieldKeyHash))
}

// KeyHashNotNil applies the NotNil predicate on the "key_hash" field.
func KeyHashNotNil() predicate.Function {
	return predicate.Function(sql.FieldNotNull(FieldKeyHash))
}

// KeyCreatedAtEQ applies the EQ predicate on the "key_created_at" field.
func KeyCreatedAtEQ(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldKeyCreatedAt, v))
}

// KeyCreatedAtNEQ applies the NEQ predicate on the "key_created_at" field.
func KeyCreatedAtNEQ(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldKeyCreatedAt, v))
}

// KeyCreatedAtIn applies the In predicate on the "key_created_at" field.
func KeyCreatedAtIn(vs ...time.Time) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldKeyCreatedAt, vs...))
}

// KeyCreatedAtNotIn applies the NotIn predicate on the "key_created_at" field.
func KeyCreatedAtNotIn(vs ...time.Time) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldKeyCreatedAt, vs...))
}

// KeyCreatedAtGT applies the GT predicate on the "key_created_at" field.
func KeyCreatedAtGT(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldKeyCreatedAt, v))
}

// KeyCreatedAtGTE applies the GTE predicate on the "key_created_at" field.
func KeyCreatedAtGTE(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldKeyCreatedAt, v))
}

// KeyCreatedAtLT applies the LT predicate on the "key_created_at" field.
func KeyCreatedAtLT(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldKeyCreatedAt, v))
}

// KeyCreatedAtLTE applies the LTE predicate on the "key_created_at" field.
func KeyCreatedAtLTE(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldKeyCreatedAt, v))
}

// KeyCreatedAtIsNil applies the IsNil predicate on the "key_created_at" field.
func KeyCreatedAtIsNil() predicate.Function {
	return predicate.Function(sql.FieldIsNull(FieldKeyCreatedAt))
}

// KeyCreatedAtNotNil applies the NotNil predicate on the "key_created_at" field.
func KeyCreatedAtNotNil() predicate.Function {
	return predicate.Function(sql.FieldNotNull(FieldKeyCreatedAt))
}

// KeyExpiresAtEQ applies the EQ predicate on the "key_expires_at" field.
func KeyExpiresAtEQ(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldKeyExpiresAt, v))
}

// KeyExpiresAtNEQ applies the NEQ predicate on the "key_expires_at" field.
func KeyExpiresAtNEQ(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldKeyExpiresAt, v))
}

// KeyExpiresAtIn applies the In predicate on the "key_expires_at" field.
func KeyExpiresAtIn(vs ...time.Time) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldKeyExpiresAt, vs...))
}

// KeyExpiresAtNotIn applies the NotIn predicate on the "key_expires_at" field.
func KeyExpiresAtNotIn(vs ...time.Time) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldKeyExpiresAt, vs...))
}

// KeyExpiresAtGT applies the GT predicate on the "key_expires_at" field.
func KeyExpiresAtGT(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldKeyExpiresAt, v))
}

// KeyExpiresAtGTE applies the GTE predicate on the "key_expires_at" field.
func KeyExpiresAtGTE(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldKeyExpiresAt, v))
}

// KeyExpiresAtLT applies the LT predicate on the "key_expires_at" field.
func KeyExpiresAtLT(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldKeyExpiresAt, v))
}

// KeyExpiresAtLTE applies the LTE predicate on the "key_expires_at" field.
func KeyExpiresAtLTE(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldKeyExpiresAt, v))
}

// KeyExpiresAtIsNil applies the IsNil predicate on the "key_expires_at" field.
func KeyExpiresAtIsNil() predicate.Function {
	return predicate.Function(sql.FieldIsNull(FieldKeyExpiresAt))
}

// KeyExpiresAtNotNil applies the NotNil predicate on the "key_expires_at" field.
func KeyExpiresAtNotNil() predicate.Function {
	return predicate.Function(sql.FieldNotNull(FieldKeyExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Function {
	return predicate.Function(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Function {
	return predicate.Function(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Function {
	return predicate.Function(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Function {
	return predicate.Function(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Function {
	return predicate.Function(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Function) predicate.Function {
	return predicate.Function(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Function) predicate.Function {
	return predicate.Function(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Function) predicate.Function {
	return predicate.Function(sql.NotPredicates(p))
}
