// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContainersColumns holds the columns for the "containers" table.
	ContainersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "openstack_name", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_containers", Type: field.TypeUUID},
	}
	// ContainersTable holds the schema information for the "containers" table.
	ContainersTable = &schema.Table{
		Name:       "containers",
		Columns:    ContainersColumns,
		PrimaryKey: []*schema.Column{ContainersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "containers_users_containers",
				Columns:    []*schema.Column{ContainersColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// InstancesColumns holds the columns for the "instances" table.
	InstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "openstack_id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "image_id", Type: field.TypeString},
		{Name: "flavor_id", Type: field.TypeString},
		{Name: "provider_created_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key_pair_instances", Type: field.TypeUUID, Nullable: true},
		{Name: "user_instances", Type: field.TypeUUID},
	}
	// InstancesTable holds the schema information for the "instances" table.
	InstancesTable = &schema.Table{
		Name:       "instances",
		Columns:    InstancesColumns,
		PrimaryKey: []*schema.Column{InstancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "instances_key_pairs_instances",
				Columns:    []*schema.Column{InstancesColumns[9]},
				RefColumns: []*schema.Column{KeyPairsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "instances_users_instances",
				Columns:    []*schema.Column{InstancesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// KeyPairsColumns holds the columns for the "key_pairs" table.
	KeyPairsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "openstack_name", Type: field.TypeString, Unique: true},
		{Name: "fingerprint", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeString},
		{Name: "source_type", Type: field.TypeEnum, Enums: []string{"user_uploaded", "system_generated"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_keypairs", Type: field.TypeUUID},
	}
	// KeyPairsTable holds the schema information for the "key_pairs" table.
	KeyPairsTable = &schema.Table{
		Name:       "key_pairs",
		Columns:    KeyPairsColumns,
		PrimaryKey: []*schema.Column{KeyPairsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "key_pairs_users_keypairs",
				Columns:    []*schema.Column{KeyPairsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "google_id", Type: field.TypeString, Unique: true},
		{Name: "google_access_token", Type: field.TypeString},
		{Name: "google_refresh_token", Type: field.TypeString},
		{Name: "google_token_expiry", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContainersTable,
		InstancesTable,
		KeyPairsTable,
		UsersTable,
	}
)

func init() {
	ContainersTable.ForeignKeys[0].RefTable = UsersTable
	InstancesTable.ForeignKeys[0].RefTable = KeyPairsTable
	InstancesTable.ForeignKeys[1].RefTable = UsersTable
	KeyPairsTable.ForeignKeys[0].RefTable = UsersTable
}
