// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "host", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "instance_app", Type: field.TypeUUID, Unique: true},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "apps_instances_app",
				Columns:    []*schema.Column{AppsColumns[4]},
				RefColumns: []*schema.Column{InstancesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// ContainersColumns holds the columns for the "containers" table.
	ContainersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "openstack_name", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_containers", Type: field.TypeUUID},
	}
	// ContainersTable holds the schema information for the "containers" table.
	ContainersTable = &schema.Table{
		Name:       "containers",
		Columns:    ContainersColumns,
		PrimaryKey: []*schema.Column{ContainersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "containers_users_containers",
				Columns:    []*schema.Column{ContainersColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "container_name_user_containers",
				Unique:  true,
				Columns: []*schema.Column{ContainersColumns[2], ContainersColumns[5]},
			},
		},
	}
	// FunctionsColumns holds the columns for the "functions" table.
	FunctionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "wasm", Type: field.TypeBytes},
		{Name: "language", Type: field.TypeString, Default: "wasm"},
		{Name: "data_mode", Type: field.TypeBool, Default: false},
		{Name: "source", Type: field.TypeBytes, Nullable: true},
		{Name: "key_hash", Type: field.TypeBytes, Nullable: true},
		{Name: "key_created_at", Type: field.TypeTime, Nullable: true},
		{Name: "key_expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_functions", Type: field.TypeUUID},
	}
	// FunctionsTable holds the schema information for the "functions" table.
	FunctionsTable = &schema.Table{
		Name:       "functions",
		Columns:    FunctionsColumns,
		PrimaryKey: []*schema.Column{FunctionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "functions_users_functions",
				Columns:    []*schema.Column{FunctionsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "function_name_user_functions",
				Unique:  true,
				Columns: []*schema.Column{FunctionsColumns[1], FunctionsColumns[11]},
			},
		},
	}
	// InstancesColumns holds the columns for the "instances" table.
	InstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "openstack_id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "image_id", Type: field.TypeString},
		{Name: "flavor_id", Type: field.TypeString},
		{Name: "key_name", Type: field.TypeString, Default: ""},
		{Name: "note", Type: field.TypeString, Default: ""},
		{Name: "provider_created_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key_pair_instances", Type: field.TypeUUID, Nullable: true},
		{Name: "user_instances", Type: field.TypeUUID},
	}
	// InstancesTable holds the schema information for the "instances" table.
	InstancesTable = &schema.Table{
		Name:       "instances",
		Columns:    InstancesColumns,
		PrimaryKey: []*schema.Column{InstancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "instances_key_pairs_instances",
				Columns:    []*schema.Column{InstancesColumns[11]},
				RefColumns: []*schema.Column{KeyPairsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "instances_users_instances",
				Columns:    []*schema.Column{InstancesColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// KeyPairsColumns holds the columns for the "key_pairs" table.
	KeyPairsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "openstack_name", Type: field.TypeString, Unique: true},
		{Name: "fingerprint", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeString},
		{Name: "source_type", Type: field.TypeEnum, Enums: []string{"user_uploaded", "system_generated"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_keypairs", Type: field.TypeUUID},
	}
	// KeyPairsTable holds the schema information for the "key_pairs" table.
	KeyPairsTable = &schema.Table{
		Name:       "key_pairs",
		Columns:    KeyPairsColumns,
		PrimaryKey: []*schema.Column{KeyPairsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "key_pairs_users_keypairs",
				Columns:    []*schema.Column{KeyPairsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// OutboxEventsColumns holds the columns for the "outbox_events" table.
	OutboxEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "operation_id", Type: field.TypeUUID},
		{Name: "kind", Type: field.TypeString},
		{Name: "payload", Type: field.TypeString, Default: ""},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "next_attempt_at", Type: field.TypeTime},
		{Name: "lease_until", Type: field.TypeTime},
		{Name: "lease_token", Type: field.TypeString, Default: ""},
		{Name: "processed_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OutboxEventsTable holds the schema information for the "outbox_events" table.
	OutboxEventsTable = &schema.Table{
		Name:       "outbox_events",
		Columns:    OutboxEventsColumns,
		PrimaryKey: []*schema.Column{OutboxEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "outboxevent_processed_at_next_attempt_at",
				Unique:  false,
				Columns: []*schema.Column{OutboxEventsColumns[8], OutboxEventsColumns[5]},
			},
		},
	}
	// ResourceObservationsColumns holds the columns for the "resource_observations" table.
	ResourceObservationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "resource_key", Type: field.TypeString, Unique: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "consistency", Type: field.TypeString},
		{Name: "reason", Type: field.TypeString, Default: ""},
		{Name: "observed_at", Type: field.TypeTime},
	}
	// ResourceObservationsTable holds the schema information for the "resource_observations" table.
	ResourceObservationsTable = &schema.Table{
		Name:       "resource_observations",
		Columns:    ResourceObservationsColumns,
		PrimaryKey: []*schema.Column{ResourceObservationsColumns[0]},
	}
	// ResourceOperationsColumns holds the columns for the "resource_operations" table.
	ResourceOperationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "request_key", Type: field.TypeString},
		{Name: "fingerprint", Type: field.TypeString},
		{Name: "kind", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeString, Default: ""},
		{Name: "payload", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "dispatched", Type: field.TypeBool, Default: false},
		{Name: "active_key", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ResourceOperationsTable holds the schema information for the "resource_operations" table.
	ResourceOperationsTable = &schema.Table{
		Name:       "resource_operations",
		Columns:    ResourceOperationsColumns,
		PrimaryKey: []*schema.Column{ResourceOperationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "resourceoperation_owner_id_request_key",
				Unique:  true,
				Columns: []*schema.Column{ResourceOperationsColumns[1], ResourceOperationsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "google_id", Type: field.TypeString, Unique: true},
		{Name: "google_access_token", Type: field.TypeString},
		{Name: "google_refresh_token", Type: field.TypeString},
		{Name: "google_token_expiry", Type: field.TypeTime},
		{Name: "current_refresh_jti", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		ContainersTable,
		FunctionsTable,
		InstancesTable,
		KeyPairsTable,
		OutboxEventsTable,
		ResourceObservationsTable,
		ResourceOperationsTable,
		UsersTable,
	}
)

func init() {
	AppsTable.ForeignKeys[0].RefTable = InstancesTable
	ContainersTable.ForeignKeys[0].RefTable = UsersTable
	FunctionsTable.ForeignKeys[0].RefTable = UsersTable
	InstancesTable.ForeignKeys[0].RefTable = KeyPairsTable
	InstancesTable.ForeignKeys[1].RefTable = UsersTable
	KeyPairsTable.ForeignKeys[0].RefTable = UsersTable
}
