// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KHU-RETURN/rcp-server/ent/container"
	"github.com/KHU-RETURN/rcp-server/ent/predicate"
	"github.com/KHU-RETURN/rcp-server/ent/user"
	"github.com/google/uuid"
)

// ContainerUpdate is the builder for updating Container entities.
type ContainerUpdate struct {
	config
	hooks    []Hook
	mutation *ContainerMutation
}

// Where appends a list predicates to the ContainerUpdate builder.
func (_u *ContainerUpdate) Where(ps ...predicate.Container) *ContainerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOpenstackName sets the "openstack_name" field.
func (_u *ContainerUpdate) SetOpenstackName(v uuid.UUID) *ContainerUpdate {
	_u.mutation.SetOpenstackName(v)
	return _u
}

// SetNillableOpenstackName sets the "openstack_name" field if the given value is not nil.
func (_u *ContainerUpdate) SetNillableOpenstackName(v *uuid.UUID) *ContainerUpdate {
	if v != nil {
		_u.SetOpenstackName(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ContainerUpdate) SetName(v string) *ContainerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ContainerUpdate) SetNillableName(v *string) *ContainerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContainerUpdate) SetUpdatedAt(v time.Time) *ContainerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ContainerUpdate) SetOwnerID(id uuid.UUID) *ContainerUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ContainerUpdate) SetOwner(v *User) *ContainerUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ContainerMutation object of the builder.
func (_u *ContainerUpdate) Mutation() *ContainerMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ContainerUpdate) ClearOwner() *ContainerUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContainerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContainerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContainerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContainerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContainerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := container.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContainerUpdate) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Container.owner"`)
	}
	return nil
}

func (_u *ContainerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(container.Table, container.Columns, sqlgraph.NewFieldSpec(container.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OpenstackName(); ok {
		_spec.SetField(container.FieldOpenstackName, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(container.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(container.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.OwnerTable,
			Columns: []string{container.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.OwnerTable,
			Columns: []string{container.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{container.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContainerUpdateOne is the builder for updating a single Container entity.
type ContainerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContainerMutation
}

// SetOpenstackName sets the "openstack_name" field.
func (_u *ContainerUpdateOne) SetOpenstackName(v uuid.UUID) *ContainerUpdateOne {
	_u.mutation.SetOpenstackName(v)
	return _u
}

// SetNillableOpenstackName sets the "openstack_name" field if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableOpenstackName(v *uuid.UUID) *ContainerUpdateOne {
	if v != nil {
		_u.SetOpenstackName(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ContainerUpdateOne) SetName(v string) *ContainerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableName(v *string) *ContainerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContainerUpdateOne) SetUpdatedAt(v time.Time) *ContainerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ContainerUpdateOne) SetOwnerID(id uuid.UUID) *ContainerUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ContainerUpdateOne) SetOwner(v *User) *ContainerUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the ContainerMutation object of the builder.
func (_u *ContainerUpdateOne) Mutation() *ContainerMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ContainerUpdateOne) ClearOwner() *ContainerUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the ContainerUpdate builder.
func (_u *ContainerUpdateOne) Where(ps ...predicate.Container) *ContainerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContainerUpdateOne) Select(field string, fields ...string) *ContainerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Container entity.
func (_u *ContainerUpdateOne) Save(ctx context.Context) (*Container, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContainerUpdateOne) SaveX(ctx context.Context) *Container {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContainerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContainerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContainerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := container.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContainerUpdateOne) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Container.owner"`)
	}
	return nil
}

func (_u *ContainerUpdateOne) sqlSave(ctx context.Context) (_node *Container, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(container.Table, container.Columns, sqlgraph.NewFieldSpec(container.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Container.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, container.FieldID)
		for _, f := range fields {
			if !container.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != container.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OpenstackName(); ok {
		_spec.SetField(container.FieldOpenstackName, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(container.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(container.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.OwnerTable,
			Columns: []string{container.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.OwnerTable,
			Columns: []string{container.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Container{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{container.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
