// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KHU-RETURN/rcp-server/ent/container"
	"github.com/KHU-RETURN/rcp-server/ent/user"
	"github.com/google/uuid"
)

// ContainerCreate is the builder for creating a Container entity.
type ContainerCreate struct {
	config
	mutation *ContainerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOpenstackName sets the "openstack_name" field.
func (_c *ContainerCreate) SetOpenstackName(v uuid.UUID) *ContainerCreate {
	_c.mutation.SetOpenstackName(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ContainerCreate) SetName(v string) *ContainerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContainerCreate) SetCreatedAt(v time.Time) *ContainerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContainerCreate) SetNillableCreatedAt(v *time.Time) *ContainerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContainerCreate) SetUpdatedAt(v time.Time) *ContainerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContainerCreate) SetNillableUpdatedAt(v *time.Time) *ContainerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ContainerCreate) SetID(v uuid.UUID) *ContainerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ContainerCreate) SetNillableID(v *uuid.UUID) *ContainerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *ContainerCreate) SetOwnerID(id uuid.UUID) *ContainerCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *ContainerCreate) SetOwner(v *User) *ContainerCreate {
	return _c.SetOwnerID(v.ID)
}

// Mutation returns the ContainerMutation object of the builder.
func (_c *ContainerCreate) Mutation() *ContainerMutation {
	return _c.mutation
}

// Save creates the Container in the database.
func (_c *ContainerCreate) Save(ctx context.Context) (*Container, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContainerCreate) SaveX(ctx context.Context) *Container {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContainerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContainerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContainerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := container.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := container.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := container.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContainerCreate) check() error {
	if _, ok := _c.mutation.OpenstackName(); !ok {
		return &ValidationError{Name: "openstack_name", err: errors.New(`ent: missing required field "Container.openstack_name"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Container.name"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Container.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Container.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Container.owner"`)}
	}
	return nil
}

func (_c *ContainerCreate) sqlSave(ctx context.Context) (*Container, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContainerCreate) createSpec() (*Container, *sqlgraph.CreateSpec) {
	var (
		_node = &Container{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(container.Table, sqlgraph.NewFieldSpec(container.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OpenstackName(); ok {
		_spec.SetField(container.FieldOpenstackName, field.TypeUUID, value)
		_node.OpenstackName = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(container.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(container.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(container.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.OwnerTable,
			Columns: []string{container.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_containers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Container.Create().
//		SetOpenstackName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContainerUpsert) {
//			SetOpenstackName(v+v).
//		}).
//		Exec(ctx)
func (_c *ContainerCreate) OnConflict(opts ...sql.ConflictOption) *ContainerUpsertOne {
	_c.conflict = opts
	return &ContainerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Container.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContainerCreate) OnConflictColumns(columns ...string) *ContainerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContainerUpsertOne{
		create: _c,
	}
}

type (
	// ContainerUpsertOne is the builder for "upsert"-ing
	//  one Container node.
	ContainerUpsertOne struct {
		create *ContainerCreate
	}

	// ContainerUpsert is the "OnConflict" setter.
	ContainerUpsert struct {
		*sql.UpdateSet
	}
)

// SetOpenstackName sets the "openstack_name" field.
func (u *ContainerUpsert) SetOpenstackName(v uuid.UUID) *ContainerUpsert {
	u.Set(container.FieldOpenstackName, v)
	return u
}

// UpdateOpenstackName sets the "openstack_name" field to the value that was provided on create.
func (u *ContainerUpsert) UpdateOpenstackName() *ContainerUpsert {
	u.SetExcluded(container.FieldOpenstackName)
	return u
}

// SetName sets the "name" field.
func (u *ContainerUpsert) SetName(v string) *ContainerUpsert {
	u.Set(container.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ContainerUpsert) UpdateName() *ContainerUpsert {
	u.SetExcluded(container.FieldName)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContainerUpsert) SetUpdatedAt(v time.Time) *ContainerUpsert {
	u.Set(container.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContainerUpsert) UpdateUpdatedAt() *ContainerUpsert {
	u.SetExcluded(container.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Container.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(container.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ContainerUpsertOne) UpdateNewValues() *ContainerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(container.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(container.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Container.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContainerUpsertOne) Ignore() *ContainerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContainerUpsertOne) DoNothing() *ContainerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContainerCreate.OnConflict
// documentation for more info.
func (u *ContainerUpsertOne) Update(set func(*ContainerUpsert)) *ContainerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContainerUpsert{UpdateSet: update})
	}))
	return u
}

// SetOpenstackName sets the "openstack_name" field.
func (u *ContainerUpsertOne) SetOpenstackName(v uuid.UUID) *ContainerUpsertOne {
	return u.Update(func(s *ContainerUpsert) {
		s.SetOpenstackName(v)
	})
}

// UpdateOpenstackName sets the "openstack_name" field to the value that was provided on create.
func (u *ContainerUpsertOne) UpdateOpenstackName() *ContainerUpsertOne {
	return u.Update(func(s *ContainerUpsert) {
		s.UpdateOpenstackName()
	})
}

// SetName sets the "name" field.
func (u *ContainerUpsertOne) SetName(v string) *ContainerUpsertOne {
	return u.Update(func(s *ContainerUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ContainerUpsertOne) UpdateName() *ContainerUpsertOne {
	return u.Update(func(s *ContainerUpsert) {
		s.UpdateName()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContainerUpsertOne) SetUpdatedAt(v time.Time) *ContainerUpsertOne {
	return u.Update(func(s *ContainerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContainerUpsertOne) UpdateUpdatedAt() *ContainerUpsertOne {
	return u.Update(func(s *ContainerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ContainerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContainerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContainerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContainerUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ContainerUpsertOne.ID is not supported by MySQL driver. Use ContainerUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContainerUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ContainerCreateBulk is the builder for creating many Container entities in bulk.
type ContainerCreateBulk struct {
	config
	err      error
	builders []*ContainerCreate
	conflict []sql.ConflictOption
}

// Save creates the Container entities in the database.
func (_c *ContainerCreateBulk) Save(ctx context.Context) ([]*Container, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Container, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContainerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContainerCreateBulk) SaveX(ctx context.Context) []*Container {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContainerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContainerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Container.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContainerUpsert) {
//			SetOpenstackName(v+v).
//		}).
//		Exec(ctx)
func (_c *ContainerCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContainerUpsertBulk {
	_c.conflict = opts
	return &ContainerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Container.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContainerCreateBulk) OnConflictColumns(columns ...string) *ContainerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContainerUpsertBulk{
		create: _c,
	}
}

// ContainerUpsertBulk is the builder for "upsert"-ing
// a bulk of Container nodes.
type ContainerUpsertBulk struct {
	create *ContainerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Container.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(container.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ContainerUpsertBulk) UpdateNewValues() *ContainerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(container.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(container.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Container.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContainerUpsertBulk) Ignore() *ContainerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContainerUpsertBulk) DoNothing() *ContainerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContainerCreateBulk.OnConflict
// documentation for more info.
func (u *ContainerUpsertBulk) Update(set func(*ContainerUpsert)) *ContainerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContainerUpsert{UpdateSet: update})
	}))
	return u
}

// SetOpenstackName sets the "openstack_name" field.
func (u *ContainerUpsertBulk) SetOpenstackName(v uuid.UUID) *ContainerUpsertBulk {
	return u.Update(func(s *ContainerUpsert) {
		s.SetOpenstackName(v)
	})
}

// UpdateOpenstackName sets the "openstack_name" field to the value that was provided on create.
func (u *ContainerUpsertBulk) UpdateOpenstackName() *ContainerUpsertBulk {
	return u.Update(func(s *ContainerUpsert) {
		s.UpdateOpenstackName()
	})
}

// SetName sets the "name" field.
func (u *ContainerUpsertBulk) SetName(v string) *ContainerUpsertBulk {
	return u.Update(func(s *ContainerUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ContainerUpsertBulk) UpdateName() *ContainerUpsertBulk {
	return u.Update(func(s *ContainerUpsert) {
		s.UpdateName()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ContainerUpsertBulk) SetUpdatedAt(v time.Time) *ContainerUpsertBulk {
	return u.Update(func(s *ContainerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ContainerUpsertBulk) UpdateUpdatedAt() *ContainerUpsertBulk {
	return u.Update(func(s *ContainerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ContainerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ContainerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContainerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContainerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
