// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KHU-RETURN/rcp-server/ent/function"
	"github.com/KHU-RETURN/rcp-server/ent/predicate"
	"github.com/KHU-RETURN/rcp-server/ent/user"
	"github.com/google/uuid"
)

// FunctionUpdate is the builder for updating Function entities.
type FunctionUpdate struct {
	config
	hooks    []Hook
	mutation *FunctionMutation
}

// Where appends a list predicates to the FunctionUpdate builder.
func (_u *FunctionUpdate) Where(ps ...predicate.Function) *FunctionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *FunctionUpdate) SetName(v string) *FunctionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FunctionUpdate) SetNillableName(v *string) *FunctionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWasm sets the "wasm" field.
func (_u *FunctionUpdate) SetWasm(v []byte) *FunctionUpdate {
	_u.mutation.SetWasm(v)
	return _u
}

// SetLanguage sets the "language" field.
func (_u *FunctionUpdate) SetLanguage(v string) *FunctionUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *FunctionUpdate) SetNillableLanguage(v *string) *FunctionUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetDataMode sets the "data_mode" field.
func (_u *FunctionUpdate) SetDataMode(v bool) *FunctionUpdate {
	_u.mutation.SetDataMode(v)
	return _u
}

// SetNillableDataMode sets the "data_mode" field if the given value is not nil.
func (_u *FunctionUpdate) SetNillableDataMode(v *bool) *FunctionUpdate {
	if v != nil {
		_u.SetDataMode(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *FunctionUpdate) SetSource(v []byte) *FunctionUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *FunctionUpdate) ClearSource() *FunctionUpdate {
	_u.mutation.ClearSource()
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *FunctionUpdate) SetKeyHash(v []byte) *FunctionUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// ClearKeyHash clears the value of the "key_hash" field.
func (_u *FunctionUpdate) ClearKeyHash() *FunctionUpdate {
	_u.mutation.ClearKeyHash()
	return _u
}

// SetKeyCreatedAt sets the "key_created_at" field.
func (_u *FunctionUpdate) SetKeyCreatedAt(v time.Time) *FunctionUpdate {
	_u.mutation.SetKeyCreatedAt(v)
	return _u
}

// SetNillableKeyCreatedAt sets the "key_created_at" field if the given value is not nil.
func (_u *FunctionUpdate) SetNillableKeyCreatedAt(v *time.Time) *FunctionUpdate {
	if v != nil {
		_u.SetKeyCreatedAt(*v)
	}
	return _u
}

// ClearKeyCreatedAt clears the value of the "key_created_at" field.
func (_u *FunctionUpdate) ClearKeyCreatedAt() *FunctionUpdate {
	_u.mutation.ClearKeyCreatedAt()
	return _u
}

// SetKeyExpiresAt sets the "key_expires_at" field.
func (_u *FunctionUpdate) SetKeyExpiresAt(v time.Time) *FunctionUpdate {
	_u.mutation.SetKeyExpiresAt(v)
	return _u
}

// SetNillableKeyExpiresAt sets the "key_expires_at" field if the given value is not nil.
func (_u *FunctionUpdate) SetNillableKeyExpiresAt(v *time.Time) *FunctionUpdate {
	if v != nil {
		_u.SetKeyExpiresAt(*v)
	}
	return _u
}

// ClearKeyExpiresAt clears the value of the "key_expires_at" field.
func (_u *FunctionUpdate) ClearKeyExpiresAt() *FunctionUpdate {
	_u.mutation.ClearKeyExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FunctionUpdate) SetUpdatedAt(v time.Time) *FunctionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *FunctionUpdate) SetOwnerID(id uuid.UUID) *FunctionUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *FunctionUpdate) SetOwner(v *User) *FunctionUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the FunctionMutation object of the builder.
func (_u *FunctionUpdate) Mutation() *FunctionMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *FunctionUpdate) ClearOwner() *FunctionUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FunctionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FunctionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FunctionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FunctionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FunctionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := function.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FunctionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := function.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Function.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Wasm(); ok {
		if err := function.WasmValidator(v); err != nil {
			return &ValidationError{Name: "wasm", err: fmt.Errorf(`ent: validator failed for field "Function.wasm": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Function.owner"`)
	}
	return nil
}

func (_u *FunctionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(function.Table, function.Columns, sqlgraph.NewFieldSpec(function.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(function.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Wasm(); ok {
		_spec.SetField(function.FieldWasm, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(function.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataMode(); ok {
		_spec.SetField(function.FieldDataMode, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(function.FieldSource, field.TypeBytes, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(function.FieldSource, field.TypeBytes)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(function.FieldKeyHash, field.TypeBytes, value)
	}
	if _u.mutation.KeyHashCleared() {
		_spec.ClearField(function.FieldKeyHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.KeyCreatedAt(); ok {
		_spec.SetField(function.FieldKeyCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.KeyCreatedAtCleared() {
		_spec.ClearField(function.FieldKeyCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.KeyExpiresAt(); ok {
		_spec.SetField(function.FieldKeyExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.KeyExpiresAtCleared() {
		_spec.ClearField(function.FieldKeyExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(function.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   function.OwnerTable,
			Columns: []string{function.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   function.OwnerTable,
			Columns: []string{function.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{function.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FunctionUpdateOne is the builder for updating a single Function entity.
type FunctionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FunctionMutation
}

// SetName sets the "name" field.
func (_u *FunctionUpdateOne) SetName(v string) *FunctionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FunctionUpdateOne) SetNillableName(v *string) *FunctionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetWasm sets the "wasm" field.
func (_u *FunctionUpdateOne) SetWasm(v []byte) *FunctionUpdateOne {
	_u.mutation.SetWasm(v)
	return _u
}

// SetLanguage sets the "language" field.
func (_u *FunctionUpdateOne) SetLanguage(v string) *FunctionUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *FunctionUpdateOne) SetNillableLanguage(v *string) *FunctionUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetDataMode sets the "data_mode" field.
func (_u *FunctionUpdateOne) SetDataMode(v bool) *FunctionUpdateOne {
	_u.mutation.SetDataMode(v)
	return _u
}

// SetNillableDataMode sets the "data_mode" field if the given value is not nil.
func (_u *FunctionUpdateOne) SetNillableDataMode(v *bool) *FunctionUpdateOne {
	if v != nil {
		_u.SetDataMode(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *FunctionUpdateOne) SetSource(v []byte) *FunctionUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// ClearSource clears the value of the "source" field.
func (_u *FunctionUpdateOne) ClearSource() *FunctionUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *FunctionUpdateOne) SetKeyHash(v []byte) *FunctionUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// ClearKeyHash clears the value of the "key_hash" field.
func (_u *FunctionUpdateOne) ClearKeyHash() *FunctionUpdateOne {
	_u.mutation.ClearKeyHash()
	return _u
}

// SetKeyCreatedAt sets the "key_created_at" field.
func (_u *FunctionUpdateOne) SetKeyCreatedAt(v time.Time) *FunctionUpdateOne {
	_u.mutation.SetKeyCreatedAt(v)
	return _u
}

// SetNillableKeyCreatedAt sets the "key_created_at" field if the given value is not nil.
func (_u *FunctionUpdateOne) SetNillableKeyCreatedAt(v *time.Time) *FunctionUpdateOne {
	if v != nil {
		_u.SetKeyCreatedAt(*v)
	}
	return _u
}

// ClearKeyCreatedAt clears the value of the "key_created_at" field.
func (_u *FunctionUpdateOne) ClearKeyCreatedAt() *FunctionUpdateOne {
	_u.mutation.ClearKeyCreatedAt()
	return _u
}

// SetKeyExpiresAt sets the "key_expires_at" field.
func (_u *FunctionUpdateOne) SetKeyExpiresAt(v time.Time) *FunctionUpdateOne {
	_u.mutation.SetKeyExpiresAt(v)
	return _u
}

// SetNillableKeyExpiresAt sets the "key_expires_at" field if the given value is not nil.
func (_u *FunctionUpdateOne) SetNillableKeyExpiresAt(v *time.Time) *FunctionUpdateOne {
	if v != nil {
		_u.SetKeyExpiresAt(*v)
	}
	return _u
}

// ClearKeyExpiresAt clears the value of the "key_expires_at" field.
func (_u *FunctionUpdateOne) ClearKeyExpiresAt() *FunctionUpdateOne {
	_u.mutation.ClearKeyExpiresAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FunctionUpdateOne) SetUpdatedAt(v time.Time) *FunctionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *FunctionUpdateOne) SetOwnerID(id uuid.UUID) *FunctionUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *FunctionUpdateOne) SetOwner(v *User) *FunctionUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the FunctionMutation object of the builder.
func (_u *FunctionUpdateOne) Mutation() *FunctionMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *FunctionUpdateOne) ClearOwner() *FunctionUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the FunctionUpdate builder.
func (_u *FunctionUpdateOne) Where(ps ...predicate.Function) *FunctionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FunctionUpdateOne) Select(field string, fields ...string) *FunctionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Function entity.
func (_u *FunctionUpdateOne) Save(ctx context.Context) (*Function, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FunctionUpdateOne) SaveX(ctx context.Context) *Function {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FunctionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FunctionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FunctionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := function.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FunctionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := function.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Function.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Wasm(); ok {
		if err := function.WasmValidator(v); err != nil {
			return &ValidationError{Name: "wasm", err: fmt.Errorf(`ent: validator failed for field "Function.wasm": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Function.owner"`)
	}
	return nil
}

func (_u *FunctionUpdateOne) sqlSave(ctx context.Context) (_node *Function, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(function.Table, function.Columns, sqlgraph.NewFieldSpec(function.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Function.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, function.FieldID)
		for _, f := range fields {
			if !function.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != function.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(function.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Wasm(); ok {
		_spec.SetField(function.FieldWasm, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(function.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.DataMode(); ok {
		_spec.SetField(function.FieldDataMode, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(function.FieldSource, field.TypeBytes, value)
	}
	if _u.mutation.SourceCleared() {
		_spec.ClearField(function.FieldSource, field.TypeBytes)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(function.FieldKeyHash, field.TypeBytes, value)
	}
	if _u.mutation.KeyHashCleared() {
		_spec.ClearField(function.FieldKeyHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.KeyCreatedAt(); ok {
		_spec.SetField(function.FieldKeyCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.KeyCreatedAtCleared() {
		_spec.ClearField(function.FieldKeyCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.KeyExpiresAt(); ok {
		_spec.SetField(function.FieldKeyExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.KeyExpiresAtCleared() {
		_spec.ClearField(function.FieldKeyExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(function.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   function.OwnerTable,
			Columns: []string{function.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   function.OwnerTable,
			Columns: []string{function.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Function{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{function.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
