// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KHU-RETURN/rcp-server/ent/instance"
	"github.com/KHU-RETURN/rcp-server/ent/keypair"
	"github.com/KHU-RETURN/rcp-server/ent/user"
	"github.com/google/uuid"
)

// KeyPairCreate is the builder for creating a KeyPair entity.
type KeyPairCreate struct {
	config
	mutation *KeyPairMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOpenstackName sets the "openstack_name" field.
func (_c *KeyPairCreate) SetOpenstackName(v string) *KeyPairCreate {
	_c.mutation.SetOpenstackName(v)
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *KeyPairCreate) SetFingerprint(v string) *KeyPairCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *KeyPairCreate) SetPublicKey(v string) *KeyPairCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *KeyPairCreate) SetSourceType(v keypair.SourceType) *KeyPairCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSyncState sets the "sync_state" field.
func (_c *KeyPairCreate) SetSyncState(v keypair.SyncState) *KeyPairCreate {
	_c.mutation.SetSyncState(v)
	return _c
}

// SetNillableSyncState sets the "sync_state" field if the given value is not nil.
func (_c *KeyPairCreate) SetNillableSyncState(v *keypair.SyncState) *KeyPairCreate {
	if v != nil {
		_c.SetSyncState(*v)
	}
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *KeyPairCreate) SetLastSyncedAt(v time.Time) *KeyPairCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *KeyPairCreate) SetCreatedAt(v time.Time) *KeyPairCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KeyPairCreate) SetNillableCreatedAt(v *time.Time) *KeyPairCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *KeyPairCreate) SetUpdatedAt(v time.Time) *KeyPairCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *KeyPairCreate) SetNillableUpdatedAt(v *time.Time) *KeyPairCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *KeyPairCreate) SetID(v uuid.UUID) *KeyPairCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *KeyPairCreate) SetNillableID(v *uuid.UUID) *KeyPairCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddOwnerIDs adds the "owner" edge to the User entity by IDs.
func (_c *KeyPairCreate) AddOwnerIDs(ids ...uuid.UUID) *KeyPairCreate {
	_c.mutation.AddOwnerIDs(ids...)
	return _c
}

// AddOwner adds the "owner" edges to the User entity.
func (_c *KeyPairCreate) AddOwner(v ...*User) *KeyPairCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOwnerIDs(ids...)
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by IDs.
func (_c *KeyPairCreate) AddInstanceIDs(ids ...uuid.UUID) *KeyPairCreate {
	_c.mutation.AddInstanceIDs(ids...)
	return _c
}

// AddInstances adds the "instances" edges to the Instance entity.
func (_c *KeyPairCreate) AddInstances(v ...*Instance) *KeyPairCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInstanceIDs(ids...)
}

// Mutation returns the KeyPairMutation object of the builder.
func (_c *KeyPairCreate) Mutation() *KeyPairMutation {
	return _c.mutation
}

// Save creates the KeyPair in the database.
func (_c *KeyPairCreate) Save(ctx context.Context) (*KeyPair, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KeyPairCreate) SaveX(ctx context.Context) *KeyPair {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeyPairCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeyPairCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KeyPairCreate) defaults() {
	if _, ok := _c.mutation.SyncState(); !ok {
		v := keypair.DefaultSyncState
		_c.mutation.SetSyncState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := keypair.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := keypair.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := keypair.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *KeyPairCreate) check() error {
	if _, ok := _c.mutation.OpenstackName(); !ok {
		return &ValidationError{Name: "openstack_name", err: errors.New(`ent: missing required field "KeyPair.openstack_name"`)}
	}
	if _, ok := _c.mutation.Fingerprint(); !ok {
		return &ValidationError{Name: "fingerprint", err: errors.New(`ent: missing required field "KeyPair.fingerprint"`)}
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "KeyPair.public_key"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "KeyPair.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := keypair.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "KeyPair.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SyncState(); !ok {
		return &ValidationError{Name: "sync_state", err: errors.New(`ent: missing required field "KeyPair.sync_state"`)}
	}
	if v, ok := _c.mutation.SyncState(); ok {
		if err := keypair.SyncStateValidator(v); err != nil {
			return &ValidationError{Name: "sync_state", err: fmt.Errorf(`ent: validator failed for field "KeyPair.sync_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		return &ValidationError{Name: "last_synced_at", err: errors.New(`ent: missing required field "KeyPair.last_synced_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "KeyPair.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "KeyPair.updated_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "KeyPair.owner"`)}
	}
	return nil
}

func (_c *KeyPairCreate) sqlSave(ctx context.Context) (*KeyPair, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KeyPairCreate) createSpec() (*KeyPair, *sqlgraph.CreateSpec) {
	var (
		_node = &KeyPair{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(keypair.Table, sqlgraph.NewFieldSpec(keypair.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OpenstackName(); ok {
		_spec.SetField(keypair.FieldOpenstackName, field.TypeString, value)
		_node.OpenstackName = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(keypair.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(keypair.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(keypair.FieldSourceType, field.TypeEnum, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SyncState(); ok {
		_spec.SetField(keypair.FieldSyncState, field.TypeEnum, value)
		_node.SyncState = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(keypair.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(keypair.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(keypair.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   keypair.OwnerTable,
			Columns: keypair.OwnerPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keypair.InstancesTable,
			Columns: []string{keypair.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KeyPair.Create().
//		SetOpenstackName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeyPairUpsert) {
//			SetOpenstackName(v+v).
//		}).
//		Exec(ctx)
func (_c *KeyPairCreate) OnConflict(opts ...sql.ConflictOption) *KeyPairUpsertOne {
	_c.conflict = opts
	return &KeyPairUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KeyPair.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeyPairCreate) OnConflictColumns(columns ...string) *KeyPairUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeyPairUpsertOne{
		create: _c,
	}
}

type (
	// KeyPairUpsertOne is the builder for "upsert"-ing
	//  one KeyPair node.
	KeyPairUpsertOne struct {
		create *KeyPairCreate
	}

	// KeyPairUpsert is the "OnConflict" setter.
	KeyPairUpsert struct {
		*sql.UpdateSet
	}
)

// SetOpenstackName sets the "openstack_name" field.
func (u *KeyPairUpsert) SetOpenstackName(v string) *KeyPairUpsert {
	u.Set(keypair.FieldOpenstackName, v)
	return u
}

// UpdateOpenstackName sets the "openstack_name" field to the value that was provided on create.
func (u *KeyPairUpsert) UpdateOpenstackName() *KeyPairUpsert {
	u.SetExcluded(keypair.FieldOpenstackName)
	return u
}

// SetFingerprint sets the "fingerprint" field.
func (u *KeyPairUpsert) SetFingerprint(v string) *KeyPairUpsert {
	u.Set(keypair.FieldFingerprint, v)
	return u
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *KeyPairUpsert) UpdateFingerprint() *KeyPairUpsert {
	u.SetExcluded(keypair.FieldFingerprint)
	return u
}

// SetPublicKey sets the "public_key" field.
func (u *KeyPairUpsert) SetPublicKey(v string) *KeyPairUpsert {
	u.Set(keypair.FieldPublicKey, v)
	return u
}

// UpdatePublicKey sets the "public_key" field to the value that was provided on create.
func (u *KeyPairUpsert) UpdatePublicKey() *KeyPairUpsert {
	u.SetExcluded(keypair.FieldPublicKey)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *KeyPairUpsert) SetSourceType(v keypair.SourceType) *KeyPairUpsert {
	u.Set(keypair.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *KeyPairUpsert) UpdateSourceType() *KeyPairUpsert {
	u.SetExcluded(keypair.FieldSourceType)
	return u
}

// SetSyncState sets the "sync_state" field.
func (u *KeyPairUpsert) SetSyncState(v keypair.SyncState) *KeyPairUpsert {
	u.Set(keypair.FieldSyncState, v)
	return u
}

// UpdateSyncState sets the "sync_state" field to the value that was provided on create.
func (u *KeyPairUpsert) UpdateSyncState() *KeyPairUpsert {
	u.SetExcluded(keypair.FieldSyncState)
	return u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *KeyPairUpsert) SetLastSyncedAt(v time.Time) *KeyPairUpsert {
	u.Set(keypair.FieldLastSyncedAt, v)
	return u
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *KeyPairUpsert) UpdateLastSyncedAt() *KeyPairUpsert {
	u.SetExcluded(keypair.FieldLastSyncedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KeyPairUpsert) SetUpdatedAt(v time.Time) *KeyPairUpsert {
	u.Set(keypair.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KeyPairUpsert) UpdateUpdatedAt() *KeyPairUpsert {
	u.SetExcluded(keypair.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.KeyPair.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(keypair.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeyPairUpsertOne) UpdateNewValues() *KeyPairUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(keypair.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(keypair.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KeyPair.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *KeyPairUpsertOne) Ignore() *KeyPairUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeyPairUpsertOne) DoNothing() *KeyPairUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeyPairCreate.OnConflict
// documentation for more info.
func (u *KeyPairUpsertOne) Update(set func(*KeyPairUpsert)) *KeyPairUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeyPairUpsert{UpdateSet: update})
	}))
	return u
}

// SetOpenstackName sets the "openstack_name" field.
func (u *KeyPairUpsertOne) SetOpenstackName(v string) *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetOpenstackName(v)
	})
}

// UpdateOpenstackName sets the "openstack_name" field to the value that was provided on create.
func (u *KeyPairUpsertOne) UpdateOpenstackName() *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateOpenstackName()
	})
}

// SetFingerprint sets the "fingerprint" field.
func (u *KeyPairUpsertOne) SetFingerprint(v string) *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetFingerprint(v)
	})
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *KeyPairUpsertOne) UpdateFingerprint() *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateFingerprint()
	})
}

// SetPublicKey sets the "public_key" field.
func (u *KeyPairUpsertOne) SetPublicKey(v string) *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetPublicKey(v)
	})
}

// UpdatePublicKey sets the "public_key" field to the value that was provided on create.
func (u *KeyPairUpsertOne) UpdatePublicKey() *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdatePublicKey()
	})
}

// SetSourceType sets the "source_type" field.
func (u *KeyPairUpsertOne) SetSourceType(v keypair.SourceType) *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *KeyPairUpsertOne) UpdateSourceType() *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateSourceType()
	})
}

// SetSyncState sets the "sync_state" field.
func (u *KeyPairUpsertOne) SetSyncState(v keypair.SyncState) *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetSyncState(v)
	})
}

// UpdateSyncState sets the "sync_state" field to the value that was provided on create.
func (u *KeyPairUpsertOne) UpdateSyncState() *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateSyncState()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *KeyPairUpsertOne) SetLastSyncedAt(v time.Time) *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *KeyPairUpsertOne) UpdateLastSyncedAt() *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KeyPairUpsertOne) SetUpdatedAt(v time.Time) *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KeyPairUpsertOne) UpdateUpdatedAt() *KeyPairUpsertOne {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *KeyPairUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeyPairCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeyPairUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *KeyPairUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: KeyPairUpsertOne.ID is not supported by MySQL driver. Use KeyPairUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *KeyPairUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// KeyPairCreateBulk is the builder for creating many KeyPair entities in bulk.
type KeyPairCreateBulk struct {
	config
	err      error
	builders []*KeyPairCreate
	conflict []sql.ConflictOption
}

// Save creates the KeyPair entities in the database.
func (_c *KeyPairCreateBulk) Save(ctx context.Context) ([]*KeyPair, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KeyPair, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KeyPairMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KeyPairCreateBulk) SaveX(ctx context.Context) []*KeyPair {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KeyPairCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KeyPairCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KeyPair.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KeyPairUpsert) {
//			SetOpenstackName(v+v).
//		}).
//		Exec(ctx)
func (_c *KeyPairCreateBulk) OnConflict(opts ...sql.ConflictOption) *KeyPairUpsertBulk {
	_c.conflict = opts
	return &KeyPairUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KeyPair.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KeyPairCreateBulk) OnConflictColumns(columns ...string) *KeyPairUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KeyPairUpsertBulk{
		create: _c,
	}
}

// KeyPairUpsertBulk is the builder for "upsert"-ing
// a bulk of KeyPair nodes.
type KeyPairUpsertBulk struct {
	create *KeyPairCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.KeyPair.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(keypair.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *KeyPairUpsertBulk) UpdateNewValues() *KeyPairUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(keypair.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(keypair.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KeyPair.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *KeyPairUpsertBulk) Ignore() *KeyPairUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KeyPairUpsertBulk) DoNothing() *KeyPairUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KeyPairCreateBulk.OnConflict
// documentation for more info.
func (u *KeyPairUpsertBulk) Update(set func(*KeyPairUpsert)) *KeyPairUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KeyPairUpsert{UpdateSet: update})
	}))
	return u
}

// SetOpenstackName sets the "openstack_name" field.
func (u *KeyPairUpsertBulk) SetOpenstackName(v string) *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetOpenstackName(v)
	})
}

// UpdateOpenstackName sets the "openstack_name" field to the value that was provided on create.
func (u *KeyPairUpsertBulk) UpdateOpenstackName() *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateOpenstackName()
	})
}

// SetFingerprint sets the "fingerprint" field.
func (u *KeyPairUpsertBulk) SetFingerprint(v string) *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetFingerprint(v)
	})
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *KeyPairUpsertBulk) UpdateFingerprint() *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateFingerprint()
	})
}

// SetPublicKey sets the "public_key" field.
func (u *KeyPairUpsertBulk) SetPublicKey(v string) *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetPublicKey(v)
	})
}

// UpdatePublicKey sets the "public_key" field to the value that was provided on create.
func (u *KeyPairUpsertBulk) UpdatePublicKey() *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdatePublicKey()
	})
}

// SetSourceType sets the "source_type" field.
func (u *KeyPairUpsertBulk) SetSourceType(v keypair.SourceType) *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *KeyPairUpsertBulk) UpdateSourceType() *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateSourceType()
	})
}

// SetSyncState sets the "sync_state" field.
func (u *KeyPairUpsertBulk) SetSyncState(v keypair.SyncState) *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetSyncState(v)
	})
}

// UpdateSyncState sets the "sync_state" field to the value that was provided on create.
func (u *KeyPairUpsertBulk) UpdateSyncState() *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateSyncState()
	})
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (u *KeyPairUpsertBulk) SetLastSyncedAt(v time.Time) *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetLastSyncedAt(v)
	})
}

// UpdateLastSyncedAt sets the "last_synced_at" field to the value that was provided on create.
func (u *KeyPairUpsertBulk) UpdateLastSyncedAt() *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateLastSyncedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KeyPairUpsertBulk) SetUpdatedAt(v time.Time) *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KeyPairUpsertBulk) UpdateUpdatedAt() *KeyPairUpsertBulk {
	return u.Update(func(s *KeyPairUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *KeyPairUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the KeyPairCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KeyPairCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KeyPairUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
