// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KHU-RETURN/rcp-server/internal/instance"
	"github.com/KHU-RETURN/rcp-server/internal/keypair"
	"github.com/KHU-RETURN/rcp-server/internal/predicate"
	"github.com/KHU-RETURN/rcp-server/internal/user"
	"github.com/google/uuid"
)

// KeyPairUpdate is the builder for updating KeyPair entities.
type KeyPairUpdate struct {
	config
	hooks    []Hook
	mutation *KeyPairMutation
}

// Where appends a list predicates to the KeyPairUpdate builder.
func (_u *KeyPairUpdate) Where(ps ...predicate.KeyPair) *KeyPairUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOpenstackName sets the "openstack_name" field.
func (_u *KeyPairUpdate) SetOpenstackName(v string) *KeyPairUpdate {
	_u.mutation.SetOpenstackName(v)
	return _u
}

// SetNillableOpenstackName sets the "openstack_name" field if the given value is not nil.
func (_u *KeyPairUpdate) SetNillableOpenstackName(v *string) *KeyPairUpdate {
	if v != nil {
		_u.SetOpenstackName(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *KeyPairUpdate) SetFingerprint(v string) *KeyPairUpdate {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *KeyPairUpdate) SetNillableFingerprint(v *string) *KeyPairUpdate {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *KeyPairUpdate) SetPublicKey(v string) *KeyPairUpdate {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *KeyPairUpdate) SetNillablePublicKey(v *string) *KeyPairUpdate {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *KeyPairUpdate) SetSourceType(v keypair.SourceType) *KeyPairUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *KeyPairUpdate) SetNillableSourceType(v *keypair.SourceType) *KeyPairUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSyncState sets the "sync_state" field.
func (_u *KeyPairUpdate) SetSyncState(v keypair.SyncState) *KeyPairUpdate {
	_u.mutation.SetSyncState(v)
	return _u
}

// SetNillableSyncState sets the "sync_state" field if the given value is not nil.
func (_u *KeyPairUpdate) SetNillableSyncState(v *keypair.SyncState) *KeyPairUpdate {
	if v != nil {
		_u.SetSyncState(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *KeyPairUpdate) SetLastSyncedAt(v time.Time) *KeyPairUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *KeyPairUpdate) SetNillableLastSyncedAt(v *time.Time) *KeyPairUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KeyPairUpdate) SetUpdatedAt(v time.Time) *KeyPairUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddOwnerIDs adds the "owner" edge to the User entity by IDs.
func (_u *KeyPairUpdate) AddOwnerIDs(ids ...uuid.UUID) *KeyPairUpdate {
	_u.mutation.AddOwnerIDs(ids...)
	return _u
}

// AddOwner adds the "owner" edges to the User entity.
func (_u *KeyPairUpdate) AddOwner(v ...*User) *KeyPairUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnerIDs(ids...)
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by IDs.
func (_u *KeyPairUpdate) AddInstanceIDs(ids ...uuid.UUID) *KeyPairUpdate {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the Instance entity.
func (_u *KeyPairUpdate) AddInstances(v ...*Instance) *KeyPairUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// Mutation returns the KeyPairMutation object of the builder.
func (_u *KeyPairUpdate) Mutation() *KeyPairMutation {
	return _u.mutation
}

// ClearOwner clears all "owner" edges to the User entity.
func (_u *KeyPairUpdate) ClearOwner() *KeyPairUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// RemoveOwnerIDs removes the "owner" edge to User entities by IDs.
func (_u *KeyPairUpdate) RemoveOwnerIDs(ids ...uuid.UUID) *KeyPairUpdate {
	_u.mutation.RemoveOwnerIDs(ids...)
	return _u
}

// RemoveOwner removes "owner" edges to User entities.
func (_u *KeyPairUpdate) RemoveOwner(v ...*User) *KeyPairUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnerIDs(ids...)
}

// ClearInstances clears all "instances" edges to the Instance entity.
func (_u *KeyPairUpdate) ClearInstances() *KeyPairUpdate {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to Instance entities by IDs.
func (_u *KeyPairUpdate) RemoveInstanceIDs(ids ...uuid.UUID) *KeyPairUpdate {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to Instance entities.
func (_u *KeyPairUpdate) RemoveInstances(v ...*Instance) *KeyPairUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KeyPairUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeyPairUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KeyPairUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeyPairUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KeyPairUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := keypair.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KeyPairUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := keypair.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`internal: validator failed for field "KeyPair.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncState(); ok {
		if err := keypair.SyncStateValidator(v); err != nil {
			return &ValidationError{Name: "sync_state", err: fmt.Errorf(`internal: validator failed for field "KeyPair.sync_state": %w`, err)}
		}
	}
	return nil
}

func (_u *KeyPairUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(keypair.Table, keypair.Columns, sqlgraph.NewFieldSpec(keypair.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OpenstackName(); ok {
		_spec.SetField(keypair.FieldOpenstackName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(keypair.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(keypair.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(keypair.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SyncState(); ok {
		_spec.SetField(keypair.FieldSyncState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(keypair.FieldLastSyncedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(keypair.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   keypair.OwnerTable,
			Columns: keypair.OwnerPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnerIDs(); len(nodes) > 0 && !_u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   keypair.OwnerTable,
			Columns: keypair.OwnerPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   keypair.OwnerTable,
			Columns: keypair.OwnerPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keypair.InstancesTable,
			Columns: []string{keypair.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keypair.InstancesTable,
			Columns: []string{keypair.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keypair.InstancesTable,
			Columns: []string{keypair.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keypair.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KeyPairUpdateOne is the builder for updating a single KeyPair entity.
type KeyPairUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KeyPairMutation
}

// SetOpenstackName sets the "openstack_name" field.
func (_u *KeyPairUpdateOne) SetOpenstackName(v string) *KeyPairUpdateOne {
	_u.mutation.SetOpenstackName(v)
	return _u
}

// SetNillableOpenstackName sets the "openstack_name" field if the given value is not nil.
func (_u *KeyPairUpdateOne) SetNillableOpenstackName(v *string) *KeyPairUpdateOne {
	if v != nil {
		_u.SetOpenstackName(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *KeyPairUpdateOne) SetFingerprint(v string) *KeyPairUpdateOne {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *KeyPairUpdateOne) SetNillableFingerprint(v *string) *KeyPairUpdateOne {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *KeyPairUpdateOne) SetPublicKey(v string) *KeyPairUpdateOne {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *KeyPairUpdateOne) SetNillablePublicKey(v *string) *KeyPairUpdateOne {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *KeyPairUpdateOne) SetSourceType(v keypair.SourceType) *KeyPairUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *KeyPairUpdateOne) SetNillableSourceType(v *keypair.SourceType) *KeyPairUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSyncState sets the "sync_state" field.
func (_u *KeyPairUpdateOne) SetSyncState(v keypair.SyncState) *KeyPairUpdateOne {
	_u.mutation.SetSyncState(v)
	return _u
}

// SetNillableSyncState sets the "sync_state" field if the given value is not nil.
func (_u *KeyPairUpdateOne) SetNillableSyncState(v *keypair.SyncState) *KeyPairUpdateOne {
	if v != nil {
		_u.SetSyncState(*v)
	}
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *KeyPairUpdateOne) SetLastSyncedAt(v time.Time) *KeyPairUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *KeyPairUpdateOne) SetNillableLastSyncedAt(v *time.Time) *KeyPairUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KeyPairUpdateOne) SetUpdatedAt(v time.Time) *KeyPairUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddOwnerIDs adds the "owner" edge to the User entity by IDs.
func (_u *KeyPairUpdateOne) AddOwnerIDs(ids ...uuid.UUID) *KeyPairUpdateOne {
	_u.mutation.AddOwnerIDs(ids...)
	return _u
}

// AddOwner adds the "owner" edges to the User entity.
func (_u *KeyPairUpdateOne) AddOwner(v ...*User) *KeyPairUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOwnerIDs(ids...)
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by IDs.
func (_u *KeyPairUpdateOne) AddInstanceIDs(ids ...uuid.UUID) *KeyPairUpdateOne {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the Instance entity.
func (_u *KeyPairUpdateOne) AddInstances(v ...*Instance) *KeyPairUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// Mutation returns the KeyPairMutation object of the builder.
func (_u *KeyPairUpdateOne) Mutation() *KeyPairMutation {
	return _u.mutation
}

// ClearOwner clears all "owner" edges to the User entity.
func (_u *KeyPairUpdateOne) ClearOwner() *KeyPairUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// RemoveOwnerIDs removes the "owner" edge to User entities by IDs.
func (_u *KeyPairUpdateOne) RemoveOwnerIDs(ids ...uuid.UUID) *KeyPairUpdateOne {
	_u.mutation.RemoveOwnerIDs(ids...)
	return _u
}

// RemoveOwner removes "owner" edges to User entities.
func (_u *KeyPairUpdateOne) RemoveOwner(v ...*User) *KeyPairUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOwnerIDs(ids...)
}

// ClearInstances clears all "instances" edges to the Instance entity.
func (_u *KeyPairUpdateOne) ClearInstances() *KeyPairUpdateOne {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to Instance entities by IDs.
func (_u *KeyPairUpdateOne) RemoveInstanceIDs(ids ...uuid.UUID) *KeyPairUpdateOne {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to Instance entities.
func (_u *KeyPairUpdateOne) RemoveInstances(v ...*Instance) *KeyPairUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// Where appends a list predicates to the KeyPairUpdate builder.
func (_u *KeyPairUpdateOne) Where(ps ...predicate.KeyPair) *KeyPairUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KeyPairUpdateOne) Select(field string, fields ...string) *KeyPairUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KeyPair entity.
func (_u *KeyPairUpdateOne) Save(ctx context.Context) (*KeyPair, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KeyPairUpdateOne) SaveX(ctx context.Context) *KeyPair {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KeyPairUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KeyPairUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KeyPairUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := keypair.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *KeyPairUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := keypair.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`internal: validator failed for field "KeyPair.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SyncState(); ok {
		if err := keypair.SyncStateValidator(v); err != nil {
			return &ValidationError{Name: "sync_state", err: fmt.Errorf(`internal: validator failed for field "KeyPair.sync_state": %w`, err)}
		}
	}
	return nil
}

func (_u *KeyPairUpdateOne) sqlSave(ctx context.Context) (_node *KeyPair, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(keypair.Table, keypair.Columns, sqlgraph.NewFieldSpec(keypair.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`internal: missing "KeyPair.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, keypair.FieldID)
		for _, f := range fields {
			if !keypair.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("internal: invalid field %q for query", f)}
			}
			if f != keypair.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OpenstackName(); ok {
		_spec.SetField(keypair.FieldOpenstackName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(keypair.FieldFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(keypair.FieldPublicKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(keypair.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SyncState(); ok {
		_spec.SetField(keypair.FieldSyncState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(keypair.FieldLastSyncedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(keypair.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   keypair.OwnerTable,
			Columns: keypair.OwnerPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOwnerIDs(); len(nodes) > 0 && !_u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   keypair.OwnerTable,
			Columns: keypair.OwnerPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   keypair.OwnerTable,
			Columns: keypair.OwnerPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keypair.InstancesTable,
			Columns: []string{keypair.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keypair.InstancesTable,
			Columns: []string{keypair.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   keypair.InstancesTable,
			Columns: []string{keypair.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &KeyPair{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{keypair.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
