// Code generated by ent, DO NOT EDIT.

package internal

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/KHU-RETURN/rcp-server/internal/instance"
	"github.com/KHU-RETURN/rcp-server/internal/keypair"
	"github.com/KHU-RETURN/rcp-server/internal/predicate"
	"github.com/KHU-RETURN/rcp-server/internal/user"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeInstance = "Instance"
	TypeKeyPair  = "KeyPair"
	TypeUser     = "User"
)

// InstanceMutation represents an operation that mutates the Instance nodes in the graph.
type InstanceMutation struct {
	config
	op                  Op
	typ                 string
	id                  *uuid.UUID
	openstack_id        *string
	name                *string
	status              *string
	image_id            *string
	flavor_id           *string
	fixed_ip            *string
	floating_ip         *string
	provider_created_at *time.Time
	sync_state          *instance.SyncState
	last_synced_at      *time.Time
	created_at          *time.Time
	updated_at          *time.Time
	clearedFields       map[string]struct{}
	owner               map[uuid.UUID]struct{}
	removedowner        map[uuid.UUID]struct{}
	clearedowner        bool
	keypair             *uuid.UUID
	clearedkeypair      bool
	done                bool
	oldValue            func(context.Context) (*Instance, error)
	predicates          []predicate.Instance
}

var _ ent.Mutation = (*InstanceMutation)(nil)

// instanceOption allows management of the mutation configuration using functional options.
type instanceOption func(*InstanceMutation)

// newInstanceMutation creates new mutation for the Instance entity.
func newInstanceMutation(c config, op Op, opts ...instanceOption) *InstanceMutation {
	m := &InstanceMutation{
		config:        c,
		op:            op,
		typ:           TypeInstance,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withInstanceID sets the ID field of the mutation.
func withInstanceID(id uuid.UUID) instanceOption {
	return func(m *InstanceMutation) {
		var (
			err   error
			once  sync.Once
			value *Instance
		)
		m.oldValue = func(ctx context.Context) (*Instance, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Instance.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withInstance sets the old Instance of the mutation.
func withInstance(node *Instance) instanceOption {
	return func(m *InstanceMutation) {
		m.oldValue = func(context.Context) (*Instance, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m InstanceMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m InstanceMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("internal: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Instance entities.
func (m *InstanceMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *InstanceMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *InstanceMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Instance.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetOpenstackID sets the "openstack_id" field.
func (m *InstanceMutation) SetOpenstackID(s string) {
	m.openstack_id = &s
}

// OpenstackID returns the value of the "openstack_id" field in the mutation.
func (m *InstanceMutation) OpenstackID() (r string, exists bool) {
	v := m.openstack_id
	if v == nil {
		return
	}
	return *v, true
}

// OldOpenstackID returns the old "openstack_id" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldOpenstackID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOpenstackID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOpenstackID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOpenstackID: %w", err)
	}
	return oldValue.OpenstackID, nil
}

// ResetOpenstackID resets all changes to the "openstack_id" field.
func (m *InstanceMutation) ResetOpenstackID() {
	m.openstack_id = nil
}

// SetName sets the "name" field.
func (m *InstanceMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *InstanceMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *InstanceMutation) ResetName() {
	m.name = nil
}

// SetStatus sets the "status" field.
func (m *InstanceMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *InstanceMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *InstanceMutation) ResetStatus() {
	m.status = nil
}

// SetImageID sets the "image_id" field.
func (m *InstanceMutation) SetImageID(s string) {
	m.image_id = &s
}

// ImageID returns the value of the "image_id" field in the mutation.
func (m *InstanceMutation) ImageID() (r string, exists bool) {
	v := m.image_id
	if v == nil {
		return
	}
	return *v, true
}

// OldImageID returns the old "image_id" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldImageID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImageID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImageID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImageID: %w", err)
	}
	return oldValue.ImageID, nil
}

// ResetImageID resets all changes to the "image_id" field.
func (m *InstanceMutation) ResetImageID() {
	m.image_id = nil
}

// SetFlavorID sets the "flavor_id" field.
func (m *InstanceMutation) SetFlavorID(s string) {
	m.flavor_id = &s
}

// FlavorID returns the value of the "flavor_id" field in the mutation.
func (m *InstanceMutation) FlavorID() (r string, exists bool) {
	v := m.flavor_id
	if v == nil {
		return
	}
	return *v, true
}

// OldFlavorID returns the old "flavor_id" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldFlavorID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFlavorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFlavorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFlavorID: %w", err)
	}
	return oldValue.FlavorID, nil
}

// ResetFlavorID resets all changes to the "flavor_id" field.
func (m *InstanceMutation) ResetFlavorID() {
	m.flavor_id = nil
}

// SetFixedIP sets the "fixed_ip" field.
func (m *InstanceMutation) SetFixedIP(s string) {
	m.fixed_ip = &s
}

// FixedIP returns the value of the "fixed_ip" field in the mutation.
func (m *InstanceMutation) FixedIP() (r string, exists bool) {
	v := m.fixed_ip
	if v == nil {
		return
	}
	return *v, true
}

// OldFixedIP returns the old "fixed_ip" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldFixedIP(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFixedIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFixedIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFixedIP: %w", err)
	}
	return oldValue.FixedIP, nil
}

// ClearFixedIP clears the value of the "fixed_ip" field.
func (m *InstanceMutation) ClearFixedIP() {
	m.fixed_ip = nil
	m.clearedFields[instance.FieldFixedIP] = struct{}{}
}

// FixedIPCleared returns if the "fixed_ip" field was cleared in this mutation.
func (m *InstanceMutation) FixedIPCleared() bool {
	_, ok := m.clearedFields[instance.FieldFixedIP]
	return ok
}

// ResetFixedIP resets all changes to the "fixed_ip" field.
func (m *InstanceMutation) ResetFixedIP() {
	m.fixed_ip = nil
	delete(m.clearedFields, instance.FieldFixedIP)
}

// SetFloatingIP sets the "floating_ip" field.
func (m *InstanceMutation) SetFloatingIP(s string) {
	m.floating_ip = &s
}

// FloatingIP returns the value of the "floating_ip" field in the mutation.
func (m *InstanceMutation) FloatingIP() (r string, exists bool) {
	v := m.floating_ip
	if v == nil {
		return
	}
	return *v, true
}

// OldFloatingIP returns the old "floating_ip" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldFloatingIP(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFloatingIP is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFloatingIP requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFloatingIP: %w", err)
	}
	return oldValue.FloatingIP, nil
}

// ClearFloatingIP clears the value of the "floating_ip" field.
func (m *InstanceMutation) ClearFloatingIP() {
	m.floating_ip = nil
	m.clearedFields[instance.FieldFloatingIP] = struct{}{}
}

// FloatingIPCleared returns if the "floating_ip" field was cleared in this mutation.
func (m *InstanceMutation) FloatingIPCleared() bool {
	_, ok := m.clearedFields[instance.FieldFloatingIP]
	return ok
}

// ResetFloatingIP resets all changes to the "floating_ip" field.
func (m *InstanceMutation) ResetFloatingIP() {
	m.floating_ip = nil
	delete(m.clearedFields, instance.FieldFloatingIP)
}

// SetProviderCreatedAt sets the "provider_created_at" field.
func (m *InstanceMutation) SetProviderCreatedAt(t time.Time) {
	m.provider_created_at = &t
}

// ProviderCreatedAt returns the value of the "provider_created_at" field in the mutation.
func (m *InstanceMutation) ProviderCreatedAt() (r time.Time, exists bool) {
	v := m.provider_created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldProviderCreatedAt returns the old "provider_created_at" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldProviderCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProviderCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProviderCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProviderCreatedAt: %w", err)
	}
	return oldValue.ProviderCreatedAt, nil
}

// ResetProviderCreatedAt resets all changes to the "provider_created_at" field.
func (m *InstanceMutation) ResetProviderCreatedAt() {
	m.provider_created_at = nil
}

// SetSyncState sets the "sync_state" field.
func (m *InstanceMutation) SetSyncState(is instance.SyncState) {
	m.sync_state = &is
}

// SyncState returns the value of the "sync_state" field in the mutation.
func (m *InstanceMutation) SyncState() (r instance.SyncState, exists bool) {
	v := m.sync_state
	if v == nil {
		return
	}
	return *v, true
}

// OldSyncState returns the old "sync_state" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldSyncState(ctx context.Context) (v instance.SyncState, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSyncState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSyncState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSyncState: %w", err)
	}
	return oldValue.SyncState, nil
}

// ResetSyncState resets all changes to the "sync_state" field.
func (m *InstanceMutation) ResetSyncState() {
	m.sync_state = nil
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (m *InstanceMutation) SetLastSyncedAt(t time.Time) {
	m.last_synced_at = &t
}

// LastSyncedAt returns the value of the "last_synced_at" field in the mutation.
func (m *InstanceMutation) LastSyncedAt() (r time.Time, exists bool) {
	v := m.last_synced_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastSyncedAt returns the old "last_synced_at" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldLastSyncedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastSyncedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastSyncedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastSyncedAt: %w", err)
	}
	return oldValue.LastSyncedAt, nil
}

// ResetLastSyncedAt resets all changes to the "last_synced_at" field.
func (m *InstanceMutation) ResetLastSyncedAt() {
	m.last_synced_at = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *InstanceMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *InstanceMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *InstanceMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *InstanceMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *InstanceMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Instance entity.
// If the Instance object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *InstanceMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *InstanceMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddOwnerIDs adds the "owner" edge to the User entity by ids.
func (m *InstanceMutation) AddOwnerIDs(ids ...uuid.UUID) {
	if m.owner == nil {
		m.owner = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.owner[ids[i]] = struct{}{}
	}
}

// ClearOwner clears the "owner" edge to the User entity.
func (m *InstanceMutation) ClearOwner() {
	m.clearedowner = true
}

// OwnerCleared reports if the "owner" edge to the User entity was cleared.
func (m *InstanceMutation) OwnerCleared() bool {
	return m.clearedowner
}

// RemoveOwnerIDs removes the "owner" edge to the User entity by IDs.
func (m *InstanceMutation) RemoveOwnerIDs(ids ...uuid.UUID) {
	if m.removedowner == nil {
		m.removedowner = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.owner, ids[i])
		m.removedowner[ids[i]] = struct{}{}
	}
}

// RemovedOwner returns the removed IDs of the "owner" edge to the User entity.
func (m *InstanceMutation) RemovedOwnerIDs() (ids []uuid.UUID) {
	for id := range m.removedowner {
		ids = append(ids, id)
	}
	return
}

// OwnerIDs returns the "owner" edge IDs in the mutation.
func (m *InstanceMutation) OwnerIDs() (ids []uuid.UUID) {
	for id := range m.owner {
		ids = append(ids, id)
	}
	return
}

// ResetOwner resets all changes to the "owner" edge.
func (m *InstanceMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
	m.removedowner = nil
}

// SetKeypairID sets the "keypair" edge to the KeyPair entity by id.
func (m *InstanceMutation) SetKeypairID(id uuid.UUID) {
	m.keypair = &id
}

// ClearKeypair clears the "keypair" edge to the KeyPair entity.
func (m *InstanceMutation) ClearKeypair() {
	m.clearedkeypair = true
}

// KeypairCleared reports if the "keypair" edge to the KeyPair entity was cleared.
func (m *InstanceMutation) KeypairCleared() bool {
	return m.clearedkeypair
}

// KeypairID returns the "keypair" edge ID in the mutation.
func (m *InstanceMutation) KeypairID() (id uuid.UUID, exists bool) {
	if m.keypair != nil {
		return *m.keypair, true
	}
	return
}

// KeypairIDs returns the "keypair" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// KeypairID instead. It exists only for internal usage by the builders.
func (m *InstanceMutation) KeypairIDs() (ids []uuid.UUID) {
	if id := m.keypair; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetKeypair resets all changes to the "keypair" edge.
func (m *InstanceMutation) ResetKeypair() {
	m.keypair = nil
	m.clearedkeypair = false
}

// Where appends a list predicates to the InstanceMutation builder.
func (m *InstanceMutation) Where(ps ...predicate.Instance) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the InstanceMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *InstanceMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Instance, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *InstanceMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *InstanceMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Instance).
func (m *InstanceMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *InstanceMutation) Fields() []string {
	fields := make([]string, 0, 12)
	if m.openstack_id != nil {
		fields = append(fields, instance.FieldOpenstackID)
	}
	if m.name != nil {
		fields = append(fields, instance.FieldName)
	}
	if m.status != nil {
		fields = append(fields, instance.FieldStatus)
	}
	if m.image_id != nil {
		fields = append(fields, instance.FieldImageID)
	}
	if m.flavor_id != nil {
		fields = append(fields, instance.FieldFlavorID)
	}
	if m.fixed_ip != nil {
		fields = append(fields, instance.FieldFixedIP)
	}
	if m.floating_ip != nil {
		fields = append(fields, instance.FieldFloatingIP)
	}
	if m.provider_created_at != nil {
		fields = append(fields, instance.FieldProviderCreatedAt)
	}
	if m.sync_state != nil {
		fields = append(fields, instance.FieldSyncState)
	}
	if m.last_synced_at != nil {
		fields = append(fields, instance.FieldLastSyncedAt)
	}
	if m.created_at != nil {
		fields = append(fields, instance.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, instance.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *InstanceMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case instance.FieldOpenstackID:
		return m.OpenstackID()
	case instance.FieldName:
		return m.Name()
	case instance.FieldStatus:
		return m.Status()
	case instance.FieldImageID:
		return m.ImageID()
	case instance.FieldFlavorID:
		return m.FlavorID()
	case instance.FieldFixedIP:
		return m.FixedIP()
	case instance.FieldFloatingIP:
		return m.FloatingIP()
	case instance.FieldProviderCreatedAt:
		return m.ProviderCreatedAt()
	case instance.FieldSyncState:
		return m.SyncState()
	case instance.FieldLastSyncedAt:
		return m.LastSyncedAt()
	case instance.FieldCreatedAt:
		return m.CreatedAt()
	case instance.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *InstanceMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case instance.FieldOpenstackID:
		return m.OldOpenstackID(ctx)
	case instance.FieldName:
		return m.OldName(ctx)
	case instance.FieldStatus:
		return m.OldStatus(ctx)
	case instance.FieldImageID:
		return m.OldImageID(ctx)
	case instance.FieldFlavorID:
		return m.OldFlavorID(ctx)
	case instance.FieldFixedIP:
		return m.OldFixedIP(ctx)
	case instance.FieldFloatingIP:
		return m.OldFloatingIP(ctx)
	case instance.FieldProviderCreatedAt:
		return m.OldProviderCreatedAt(ctx)
	case instance.FieldSyncState:
		return m.OldSyncState(ctx)
	case instance.FieldLastSyncedAt:
		return m.OldLastSyncedAt(ctx)
	case instance.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case instance.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Instance field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InstanceMutation) SetField(name string, value ent.Value) error {
	switch name {
	case instance.FieldOpenstackID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOpenstackID(v)
		return nil
	case instance.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case instance.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case instance.FieldImageID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImageID(v)
		return nil
	case instance.FieldFlavorID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFlavorID(v)
		return nil
	case instance.FieldFixedIP:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFixedIP(v)
		return nil
	case instance.FieldFloatingIP:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFloatingIP(v)
		return nil
	case instance.FieldProviderCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProviderCreatedAt(v)
		return nil
	case instance.FieldSyncState:
		v, ok := value.(instance.SyncState)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSyncState(v)
		return nil
	case instance.FieldLastSyncedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastSyncedAt(v)
		return nil
	case instance.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case instance.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Instance field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *InstanceMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *InstanceMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *InstanceMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Instance numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *InstanceMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(instance.FieldFixedIP) {
		fields = append(fields, instance.FieldFixedIP)
	}
	if m.FieldCleared(instance.FieldFloatingIP) {
		fields = append(fields, instance.FieldFloatingIP)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *InstanceMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *InstanceMutation) ClearField(name string) error {
	switch name {
	case instance.FieldFixedIP:
		m.ClearFixedIP()
		return nil
	case instance.FieldFloatingIP:
		m.ClearFloatingIP()
		return nil
	}
	return fmt.Errorf("unknown Instance nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *InstanceMutation) ResetField(name string) error {
	switch name {
	case instance.FieldOpenstackID:
		m.ResetOpenstackID()
		return nil
	case instance.FieldName:
		m.ResetName()
		return nil
	case instance.FieldStatus:
		m.ResetStatus()
		return nil
	case instance.FieldImageID:
		m.ResetImageID()
		return nil
	case instance.FieldFlavorID:
		m.ResetFlavorID()
		return nil
	case instance.FieldFixedIP:
		m.ResetFixedIP()
		return nil
	case instance.FieldFloatingIP:
		m.ResetFloatingIP()
		return nil
	case instance.FieldProviderCreatedAt:
		m.ResetProviderCreatedAt()
		return nil
	case instance.FieldSyncState:
		m.ResetSyncState()
		return nil
	case instance.FieldLastSyncedAt:
		m.ResetLastSyncedAt()
		return nil
	case instance.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case instance.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Instance field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *InstanceMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.owner != nil {
		edges = append(edges, instance.EdgeOwner)
	}
	if m.keypair != nil {
		edges = append(edges, instance.EdgeKeypair)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *InstanceMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case instance.EdgeOwner:
		ids := make([]ent.Value, 0, len(m.owner))
		for id := range m.owner {
			ids = append(ids, id)
		}
		return ids
	case instance.EdgeKeypair:
		if id := m.keypair; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *InstanceMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedowner != nil {
		edges = append(edges, instance.EdgeOwner)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *InstanceMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case instance.EdgeOwner:
		ids := make([]ent.Value, 0, len(m.removedowner))
		for id := range m.removedowner {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *InstanceMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedowner {
		edges = append(edges, instance.EdgeOwner)
	}
	if m.clearedkeypair {
		edges = append(edges, instance.EdgeKeypair)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *InstanceMutation) EdgeCleared(name string) bool {
	switch name {
	case instance.EdgeOwner:
		return m.clearedowner
	case instance.EdgeKeypair:
		return m.clearedkeypair
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *InstanceMutation) ClearEdge(name string) error {
	switch name {
	case instance.EdgeKeypair:
		m.ClearKeypair()
		return nil
	}
	return fmt.Errorf("unknown Instance unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *InstanceMutation) ResetEdge(name string) error {
	switch name {
	case instance.EdgeOwner:
		m.ResetOwner()
		return nil
	case instance.EdgeKeypair:
		m.ResetKeypair()
		return nil
	}
	return fmt.Errorf("unknown Instance edge %s", name)
}

// KeyPairMutation represents an operation that mutates the KeyPair nodes in the graph.
type KeyPairMutation struct {
	config
	op               Op
	typ              string
	id               *uuid.UUID
	openstack_name   *string
	fingerprint      *string
	public_key       *string
	source_type      *keypair.SourceType
	sync_state       *keypair.SyncState
	last_synced_at   *time.Time
	created_at       *time.Time
	updated_at       *time.Time
	clearedFields    map[string]struct{}
	owner            map[uuid.UUID]struct{}
	removedowner     map[uuid.UUID]struct{}
	clearedowner     bool
	instances        map[uuid.UUID]struct{}
	removedinstances map[uuid.UUID]struct{}
	clearedinstances bool
	done             bool
	oldValue         func(context.Context) (*KeyPair, error)
	predicates       []predicate.KeyPair
}

var _ ent.Mutation = (*KeyPairMutation)(nil)

// keypairOption allows management of the mutation configuration using functional options.
type keypairOption func(*KeyPairMutation)

// newKeyPairMutation creates new mutation for the KeyPair entity.
func newKeyPairMutation(c config, op Op, opts ...keypairOption) *KeyPairMutation {
	m := &KeyPairMutation{
		config:        c,
		op:            op,
		typ:           TypeKeyPair,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withKeyPairID sets the ID field of the mutation.
func withKeyPairID(id uuid.UUID) keypairOption {
	return func(m *KeyPairMutation) {
		var (
			err   error
			once  sync.Once
			value *KeyPair
		)
		m.oldValue = func(ctx context.Context) (*KeyPair, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().KeyPair.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withKeyPair sets the old KeyPair of the mutation.
func withKeyPair(node *KeyPair) keypairOption {
	return func(m *KeyPairMutation) {
		m.oldValue = func(context.Context) (*KeyPair, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m KeyPairMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m KeyPairMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("internal: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of KeyPair entities.
func (m *KeyPairMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *KeyPairMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *KeyPairMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().KeyPair.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetOpenstackName sets the "openstack_name" field.
func (m *KeyPairMutation) SetOpenstackName(s string) {
	m.openstack_name = &s
}

// OpenstackName returns the value of the "openstack_name" field in the mutation.
func (m *KeyPairMutation) OpenstackName() (r string, exists bool) {
	v := m.openstack_name
	if v == nil {
		return
	}
	return *v, true
}

// OldOpenstackName returns the old "openstack_name" field's value of the KeyPair entity.
// If the KeyPair object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KeyPairMutation) OldOpenstackName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOpenstackName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOpenstackName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOpenstackName: %w", err)
	}
	return oldValue.OpenstackName, nil
}

// ResetOpenstackName resets all changes to the "openstack_name" field.
func (m *KeyPairMutation) ResetOpenstackName() {
	m.openstack_name = nil
}

// SetFingerprint sets the "fingerprint" field.
func (m *KeyPairMutation) SetFingerprint(s string) {
	m.fingerprint = &s
}

// Fingerprint returns the value of the "fingerprint" field in the mutation.
func (m *KeyPairMutation) Fingerprint() (r string, exists bool) {
	v := m.fingerprint
	if v == nil {
		return
	}
	return *v, true
}

// OldFingerprint returns the old "fingerprint" field's value of the KeyPair entity.
// If the KeyPair object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KeyPairMutation) OldFingerprint(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFingerprint is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFingerprint requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFingerprint: %w", err)
	}
	return oldValue.Fingerprint, nil
}

// ResetFingerprint resets all changes to the "fingerprint" field.
func (m *KeyPairMutation) ResetFingerprint() {
	m.fingerprint = nil
}

// SetPublicKey sets the "public_key" field.
func (m *KeyPairMutation) SetPublicKey(s string) {
	m.public_key = &s
}

// PublicKey returns the value of the "public_key" field in the mutation.
func (m *KeyPairMutation) PublicKey() (r string, exists bool) {
	v := m.public_key
	if v == nil {
		return
	}
	return *v, true
}

// OldPublicKey returns the old "public_key" field's value of the KeyPair entity.
// If the KeyPair object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KeyPairMutation) OldPublicKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublicKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublicKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublicKey: %w", err)
	}
	return oldValue.PublicKey, nil
}

// ResetPublicKey resets all changes to the "public_key" field.
func (m *KeyPairMutation) ResetPublicKey() {
	m.public_key = nil
}

// SetSourceType sets the "source_type" field.
func (m *KeyPairMutation) SetSourceType(kt keypair.SourceType) {
	m.source_type = &kt
}

// SourceType returns the value of the "source_type" field in the mutation.
func (m *KeyPairMutation) SourceType() (r keypair.SourceType, exists bool) {
	v := m.source_type
	if v == nil {
		return
	}
	return *v, true
}

// OldSourceType returns the old "source_type" field's value of the KeyPair entity.
// If the KeyPair object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KeyPairMutation) OldSourceType(ctx context.Context) (v keypair.SourceType, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSourceType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSourceType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSourceType: %w", err)
	}
	return oldValue.SourceType, nil
}

// ResetSourceType resets all changes to the "source_type" field.
func (m *KeyPairMutation) ResetSourceType() {
	m.source_type = nil
}

// SetSyncState sets the "sync_state" field.
func (m *KeyPairMutation) SetSyncState(ks keypair.SyncState) {
	m.sync_state = &ks
}

// SyncState returns the value of the "sync_state" field in the mutation.
func (m *KeyPairMutation) SyncState() (r keypair.SyncState, exists bool) {
	v := m.sync_state
	if v == nil {
		return
	}
	return *v, true
}

// OldSyncState returns the old "sync_state" field's value of the KeyPair entity.
// If the KeyPair object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KeyPairMutation) OldSyncState(ctx context.Context) (v keypair.SyncState, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSyncState is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSyncState requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSyncState: %w", err)
	}
	return oldValue.SyncState, nil
}

// ResetSyncState resets all changes to the "sync_state" field.
func (m *KeyPairMutation) ResetSyncState() {
	m.sync_state = nil
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (m *KeyPairMutation) SetLastSyncedAt(t time.Time) {
	m.last_synced_at = &t
}

// LastSyncedAt returns the value of the "last_synced_at" field in the mutation.
func (m *KeyPairMutation) LastSyncedAt() (r time.Time, exists bool) {
	v := m.last_synced_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastSyncedAt returns the old "last_synced_at" field's value of the KeyPair entity.
// If the KeyPair object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KeyPairMutation) OldLastSyncedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastSyncedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastSyncedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastSyncedAt: %w", err)
	}
	return oldValue.LastSyncedAt, nil
}

// ResetLastSyncedAt resets all changes to the "last_synced_at" field.
func (m *KeyPairMutation) ResetLastSyncedAt() {
	m.last_synced_at = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *KeyPairMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *KeyPairMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the KeyPair entity.
// If the KeyPair object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KeyPairMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *KeyPairMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *KeyPairMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *KeyPairMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the KeyPair entity.
// If the KeyPair object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *KeyPairMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *KeyPairMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddOwnerIDs adds the "owner" edge to the User entity by ids.
func (m *KeyPairMutation) AddOwnerIDs(ids ...uuid.UUID) {
	if m.owner == nil {
		m.owner = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.owner[ids[i]] = struct{}{}
	}
}

// ClearOwner clears the "owner" edge to the User entity.
func (m *KeyPairMutation) ClearOwner() {
	m.clearedowner = true
}

// OwnerCleared reports if the "owner" edge to the User entity was cleared.
func (m *KeyPairMutation) OwnerCleared() bool {
	return m.clearedowner
}

// RemoveOwnerIDs removes the "owner" edge to the User entity by IDs.
func (m *KeyPairMutation) RemoveOwnerIDs(ids ...uuid.UUID) {
	if m.removedowner == nil {
		m.removedowner = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.owner, ids[i])
		m.removedowner[ids[i]] = struct{}{}
	}
}

// RemovedOwner returns the removed IDs of the "owner" edge to the User entity.
func (m *KeyPairMutation) RemovedOwnerIDs() (ids []uuid.UUID) {
	for id := range m.removedowner {
		ids = append(ids, id)
	}
	return
}

// OwnerIDs returns the "owner" edge IDs in the mutation.
func (m *KeyPairMutation) OwnerIDs() (ids []uuid.UUID) {
	for id := range m.owner {
		ids = append(ids, id)
	}
	return
}

// ResetOwner resets all changes to the "owner" edge.
func (m *KeyPairMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
	m.removedowner = nil
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by ids.
func (m *KeyPairMutation) AddInstanceIDs(ids ...uuid.UUID) {
	if m.instances == nil {
		m.instances = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.instances[ids[i]] = struct{}{}
	}
}

// ClearInstances clears the "instances" edge to the Instance entity.
func (m *KeyPairMutation) ClearInstances() {
	m.clearedinstances = true
}

// InstancesCleared reports if the "instances" edge to the Instance entity was cleared.
func (m *KeyPairMutation) InstancesCleared() bool {
	return m.clearedinstances
}

// RemoveInstanceIDs removes the "instances" edge to the Instance entity by IDs.
func (m *KeyPairMutation) RemoveInstanceIDs(ids ...uuid.UUID) {
	if m.removedinstances == nil {
		m.removedinstances = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.instances, ids[i])
		m.removedinstances[ids[i]] = struct{}{}
	}
}

// RemovedInstances returns the removed IDs of the "instances" edge to the Instance entity.
func (m *KeyPairMutation) RemovedInstancesIDs() (ids []uuid.UUID) {
	for id := range m.removedinstances {
		ids = append(ids, id)
	}
	return
}

// InstancesIDs returns the "instances" edge IDs in the mutation.
func (m *KeyPairMutation) InstancesIDs() (ids []uuid.UUID) {
	for id := range m.instances {
		ids = append(ids, id)
	}
	return
}

// ResetInstances resets all changes to the "instances" edge.
func (m *KeyPairMutation) ResetInstances() {
	m.instances = nil
	m.clearedinstances = false
	m.removedinstances = nil
}

// Where appends a list predicates to the KeyPairMutation builder.
func (m *KeyPairMutation) Where(ps ...predicate.KeyPair) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the KeyPairMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *KeyPairMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.KeyPair, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *KeyPairMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *KeyPairMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (KeyPair).
func (m *KeyPairMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *KeyPairMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.openstack_name != nil {
		fields = append(fields, keypair.FieldOpenstackName)
	}
	if m.fingerprint != nil {
		fields = append(fields, keypair.FieldFingerprint)
	}
	if m.public_key != nil {
		fields = append(fields, keypair.FieldPublicKey)
	}
	if m.source_type != nil {
		fields = append(fields, keypair.FieldSourceType)
	}
	if m.sync_state != nil {
		fields = append(fields, keypair.FieldSyncState)
	}
	if m.last_synced_at != nil {
		fields = append(fields, keypair.FieldLastSyncedAt)
	}
	if m.created_at != nil {
		fields = append(fields, keypair.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, keypair.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *KeyPairMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case keypair.FieldOpenstackName:
		return m.OpenstackName()
	case keypair.FieldFingerprint:
		return m.Fingerprint()
	case keypair.FieldPublicKey:
		return m.PublicKey()
	case keypair.FieldSourceType:
		return m.SourceType()
	case keypair.FieldSyncState:
		return m.SyncState()
	case keypair.FieldLastSyncedAt:
		return m.LastSyncedAt()
	case keypair.FieldCreatedAt:
		return m.CreatedAt()
	case keypair.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *KeyPairMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case keypair.FieldOpenstackName:
		return m.OldOpenstackName(ctx)
	case keypair.FieldFingerprint:
		return m.OldFingerprint(ctx)
	case keypair.FieldPublicKey:
		return m.OldPublicKey(ctx)
	case keypair.FieldSourceType:
		return m.OldSourceType(ctx)
	case keypair.FieldSyncState:
		return m.OldSyncState(ctx)
	case keypair.FieldLastSyncedAt:
		return m.OldLastSyncedAt(ctx)
	case keypair.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case keypair.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown KeyPair field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *KeyPairMutation) SetField(name string, value ent.Value) error {
	switch name {
	case keypair.FieldOpenstackName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOpenstackName(v)
		return nil
	case keypair.FieldFingerprint:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFingerprint(v)
		return nil
	case keypair.FieldPublicKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublicKey(v)
		return nil
	case keypair.FieldSourceType:
		v, ok := value.(keypair.SourceType)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSourceType(v)
		return nil
	case keypair.FieldSyncState:
		v, ok := value.(keypair.SyncState)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSyncState(v)
		return nil
	case keypair.FieldLastSyncedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastSyncedAt(v)
		return nil
	case keypair.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case keypair.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown KeyPair field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *KeyPairMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *KeyPairMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *KeyPairMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown KeyPair numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *KeyPairMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *KeyPairMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *KeyPairMutation) ClearField(name string) error {
	return fmt.Errorf("unknown KeyPair nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *KeyPairMutation) ResetField(name string) error {
	switch name {
	case keypair.FieldOpenstackName:
		m.ResetOpenstackName()
		return nil
	case keypair.FieldFingerprint:
		m.ResetFingerprint()
		return nil
	case keypair.FieldPublicKey:
		m.ResetPublicKey()
		return nil
	case keypair.FieldSourceType:
		m.ResetSourceType()
		return nil
	case keypair.FieldSyncState:
		m.ResetSyncState()
		return nil
	case keypair.FieldLastSyncedAt:
		m.ResetLastSyncedAt()
		return nil
	case keypair.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case keypair.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown KeyPair field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *KeyPairMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.owner != nil {
		edges = append(edges, keypair.EdgeOwner)
	}
	if m.instances != nil {
		edges = append(edges, keypair.EdgeInstances)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *KeyPairMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case keypair.EdgeOwner:
		ids := make([]ent.Value, 0, len(m.owner))
		for id := range m.owner {
			ids = append(ids, id)
		}
		return ids
	case keypair.EdgeInstances:
		ids := make([]ent.Value, 0, len(m.instances))
		for id := range m.instances {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *KeyPairMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedowner != nil {
		edges = append(edges, keypair.EdgeOwner)
	}
	if m.removedinstances != nil {
		edges = append(edges, keypair.EdgeInstances)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *KeyPairMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case keypair.EdgeOwner:
		ids := make([]ent.Value, 0, len(m.removedowner))
		for id := range m.removedowner {
			ids = append(ids, id)
		}
		return ids
	case keypair.EdgeInstances:
		ids := make([]ent.Value, 0, len(m.removedinstances))
		for id := range m.removedinstances {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *KeyPairMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedowner {
		edges = append(edges, keypair.EdgeOwner)
	}
	if m.clearedinstances {
		edges = append(edges, keypair.EdgeInstances)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *KeyPairMutation) EdgeCleared(name string) bool {
	switch name {
	case keypair.EdgeOwner:
		return m.clearedowner
	case keypair.EdgeInstances:
		return m.clearedinstances
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *KeyPairMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown KeyPair unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *KeyPairMutation) ResetEdge(name string) error {
	switch name {
	case keypair.EdgeOwner:
		m.ResetOwner()
		return nil
	case keypair.EdgeInstances:
		m.ResetInstances()
		return nil
	}
	return fmt.Errorf("unknown KeyPair edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op                   Op
	typ                  string
	id                   *uuid.UUID
	email                *string
	name                 *string
	google_id            *string
	google_access_token  *string
	google_refresh_token *string
	google_token_expiry  *time.Time
	created_at           *time.Time
	updated_at           *time.Time
	clearedFields        map[string]struct{}
	instances            map[uuid.UUID]struct{}
	removedinstances     map[uuid.UUID]struct{}
	clearedinstances     bool
	keypairs             map[uuid.UUID]struct{}
	removedkeypairs      map[uuid.UUID]struct{}
	clearedkeypairs      bool
	done                 bool
	oldValue             func(context.Context) (*User, error)
	predicates           []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id uuid.UUID) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("internal: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id uuid.UUID) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id uuid.UUID, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]uuid.UUID, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uuid.UUID{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetEmail sets the "email" field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
}

// SetName sets the "name" field.
func (m *UserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *UserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *UserMutation) ResetName() {
	m.name = nil
}

// SetGoogleID sets the "google_id" field.
func (m *UserMutation) SetGoogleID(s string) {
	m.google_id = &s
}

// GoogleID returns the value of the "google_id" field in the mutation.
func (m *UserMutation) GoogleID() (r string, exists bool) {
	v := m.google_id
	if v == nil {
		return
	}
	return *v, true
}

// OldGoogleID returns the old "google_id" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldGoogleID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGoogleID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGoogleID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGoogleID: %w", err)
	}
	return oldValue.GoogleID, nil
}

// ResetGoogleID resets all changes to the "google_id" field.
func (m *UserMutation) ResetGoogleID() {
	m.google_id = nil
}

// SetGoogleAccessToken sets the "google_access_token" field.
func (m *UserMutation) SetGoogleAccessToken(s string) {
	m.google_access_token = &s
}

// GoogleAccessToken returns the value of the "google_access_token" field in the mutation.
func (m *UserMutation) GoogleAccessToken() (r string, exists bool) {
	v := m.google_access_token
	if v == nil {
		return
	}
	return *v, true
}

// OldGoogleAccessToken returns the old "google_access_token" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldGoogleAccessToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGoogleAccessToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGoogleAccessToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGoogleAccessToken: %w", err)
	}
	return oldValue.GoogleAccessToken, nil
}

// ResetGoogleAccessToken resets all changes to the "google_access_token" field.
func (m *UserMutation) ResetGoogleAccessToken() {
	m.google_access_token = nil
}

// SetGoogleRefreshToken sets the "google_refresh_token" field.
func (m *UserMutation) SetGoogleRefreshToken(s string) {
	m.google_refresh_token = &s
}

// GoogleRefreshToken returns the value of the "google_refresh_token" field in the mutation.
func (m *UserMutation) GoogleRefreshToken() (r string, exists bool) {
	v := m.google_refresh_token
	if v == nil {
		return
	}
	return *v, true
}

// OldGoogleRefreshToken returns the old "google_refresh_token" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldGoogleRefreshToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGoogleRefreshToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGoogleRefreshToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGoogleRefreshToken: %w", err)
	}
	return oldValue.GoogleRefreshToken, nil
}

// ResetGoogleRefreshToken resets all changes to the "google_refresh_token" field.
func (m *UserMutation) ResetGoogleRefreshToken() {
	m.google_refresh_token = nil
}

// SetGoogleTokenExpiry sets the "google_token_expiry" field.
func (m *UserMutation) SetGoogleTokenExpiry(t time.Time) {
	m.google_token_expiry = &t
}

// GoogleTokenExpiry returns the value of the "google_token_expiry" field in the mutation.
func (m *UserMutation) GoogleTokenExpiry() (r time.Time, exists bool) {
	v := m.google_token_expiry
	if v == nil {
		return
	}
	return *v, true
}

// OldGoogleTokenExpiry returns the old "google_token_expiry" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldGoogleTokenExpiry(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGoogleTokenExpiry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGoogleTokenExpiry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGoogleTokenExpiry: %w", err)
	}
	return oldValue.GoogleTokenExpiry, nil
}

// ResetGoogleTokenExpiry resets all changes to the "google_token_expiry" field.
func (m *UserMutation) ResetGoogleTokenExpiry() {
	m.google_token_expiry = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *UserMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *UserMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *UserMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *UserMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *UserMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *UserMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by ids.
func (m *UserMutation) AddInstanceIDs(ids ...uuid.UUID) {
	if m.instances == nil {
		m.instances = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.instances[ids[i]] = struct{}{}
	}
}

// ClearInstances clears the "instances" edge to the Instance entity.
func (m *UserMutation) ClearInstances() {
	m.clearedinstances = true
}

// InstancesCleared reports if the "instances" edge to the Instance entity was cleared.
func (m *UserMutation) InstancesCleared() bool {
	return m.clearedinstances
}

// RemoveInstanceIDs removes the "instances" edge to the Instance entity by IDs.
func (m *UserMutation) RemoveInstanceIDs(ids ...uuid.UUID) {
	if m.removedinstances == nil {
		m.removedinstances = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.instances, ids[i])
		m.removedinstances[ids[i]] = struct{}{}
	}
}

// RemovedInstances returns the removed IDs of the "instances" edge to the Instance entity.
func (m *UserMutation) RemovedInstancesIDs() (ids []uuid.UUID) {
	for id := range m.removedinstances {
		ids = append(ids, id)
	}
	return
}

// InstancesIDs returns the "instances" edge IDs in the mutation.
func (m *UserMutation) InstancesIDs() (ids []uuid.UUID) {
	for id := range m.instances {
		ids = append(ids, id)
	}
	return
}

// ResetInstances resets all changes to the "instances" edge.
func (m *UserMutation) ResetInstances() {
	m.instances = nil
	m.clearedinstances = false
	m.removedinstances = nil
}

// AddKeypairIDs adds the "keypairs" edge to the KeyPair entity by ids.
func (m *UserMutation) AddKeypairIDs(ids ...uuid.UUID) {
	if m.keypairs == nil {
		m.keypairs = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		m.keypairs[ids[i]] = struct{}{}
	}
}

// ClearKeypairs clears the "keypairs" edge to the KeyPair entity.
func (m *UserMutation) ClearKeypairs() {
	m.clearedkeypairs = true
}

// KeypairsCleared reports if the "keypairs" edge to the KeyPair entity was cleared.
func (m *UserMutation) KeypairsCleared() bool {
	return m.clearedkeypairs
}

// RemoveKeypairIDs removes the "keypairs" edge to the KeyPair entity by IDs.
func (m *UserMutation) RemoveKeypairIDs(ids ...uuid.UUID) {
	if m.removedkeypairs == nil {
		m.removedkeypairs = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		delete(m.keypairs, ids[i])
		m.removedkeypairs[ids[i]] = struct{}{}
	}
}

// RemovedKeypairs returns the removed IDs of the "keypairs" edge to the KeyPair entity.
func (m *UserMutation) RemovedKeypairsIDs() (ids []uuid.UUID) {
	for id := range m.removedkeypairs {
		ids = append(ids, id)
	}
	return
}

// KeypairsIDs returns the "keypairs" edge IDs in the mutation.
func (m *UserMutation) KeypairsIDs() (ids []uuid.UUID) {
	for id := range m.keypairs {
		ids = append(ids, id)
	}
	return
}

// ResetKeypairs resets all changes to the "keypairs" edge.
func (m *UserMutation) ResetKeypairs() {
	m.keypairs = nil
	m.clearedkeypairs = false
	m.removedkeypairs = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	if m.name != nil {
		fields = append(fields, user.FieldName)
	}
	if m.google_id != nil {
		fields = append(fields, user.FieldGoogleID)
	}
	if m.google_access_token != nil {
		fields = append(fields, user.FieldGoogleAccessToken)
	}
	if m.google_refresh_token != nil {
		fields = append(fields, user.FieldGoogleRefreshToken)
	}
	if m.google_token_expiry != nil {
		fields = append(fields, user.FieldGoogleTokenExpiry)
	}
	if m.created_at != nil {
		fields = append(fields, user.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, user.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldEmail:
		return m.Email()
	case user.FieldName:
		return m.Name()
	case user.FieldGoogleID:
		return m.GoogleID()
	case user.FieldGoogleAccessToken:
		return m.GoogleAccessToken()
	case user.FieldGoogleRefreshToken:
		return m.GoogleRefreshToken()
	case user.FieldGoogleTokenExpiry:
		return m.GoogleTokenExpiry()
	case user.FieldCreatedAt:
		return m.CreatedAt()
	case user.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldEmail:
		return m.OldEmail(ctx)
	case user.FieldName:
		return m.OldName(ctx)
	case user.FieldGoogleID:
		return m.OldGoogleID(ctx)
	case user.FieldGoogleAccessToken:
		return m.OldGoogleAccessToken(ctx)
	case user.FieldGoogleRefreshToken:
		return m.OldGoogleRefreshToken(ctx)
	case user.FieldGoogleTokenExpiry:
		return m.OldGoogleTokenExpiry(ctx)
	case user.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case user.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case user.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case user.FieldGoogleID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGoogleID(v)
		return nil
	case user.FieldGoogleAccessToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGoogleAccessToken(v)
		return nil
	case user.FieldGoogleRefreshToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGoogleRefreshToken(v)
		return nil
	case user.FieldGoogleTokenExpiry:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGoogleTokenExpiry(v)
		return nil
	case user.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case user.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	case user.FieldName:
		m.ResetName()
		return nil
	case user.FieldGoogleID:
		m.ResetGoogleID()
		return nil
	case user.FieldGoogleAccessToken:
		m.ResetGoogleAccessToken()
		return nil
	case user.FieldGoogleRefreshToken:
		m.ResetGoogleRefreshToken()
		return nil
	case user.FieldGoogleTokenExpiry:
		m.ResetGoogleTokenExpiry()
		return nil
	case user.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case user.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.instances != nil {
		edges = append(edges, user.EdgeInstances)
	}
	if m.keypairs != nil {
		edges = append(edges, user.EdgeKeypairs)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeInstances:
		ids := make([]ent.Value, 0, len(m.instances))
		for id := range m.instances {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeKeypairs:
		ids := make([]ent.Value, 0, len(m.keypairs))
		for id := range m.keypairs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedinstances != nil {
		edges = append(edges, user.EdgeInstances)
	}
	if m.removedkeypairs != nil {
		edges = append(edges, user.EdgeKeypairs)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeInstances:
		ids := make([]ent.Value, 0, len(m.removedinstances))
		for id := range m.removedinstances {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeKeypairs:
		ids := make([]ent.Value, 0, len(m.removedkeypairs))
		for id := range m.removedkeypairs {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedinstances {
		edges = append(edges, user.EdgeInstances)
	}
	if m.clearedkeypairs {
		edges = append(edges, user.EdgeKeypairs)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeInstances:
		return m.clearedinstances
	case user.EdgeKeypairs:
		return m.clearedkeypairs
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeInstances:
		m.ResetInstances()
		return nil
	case user.EdgeKeypairs:
		m.ResetKeypairs()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
