// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KHU-RETURN/rcp-server/ent/outboxevent"
	"github.com/google/uuid"
)

// OutboxEventCreate is the builder for creating a OutboxEvent entity.
type OutboxEventCreate struct {
	config
	mutation *OutboxEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOperationID sets the "operation_id" field.
func (_c *OutboxEventCreate) SetOperationID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetOperationID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *OutboxEventCreate) SetKind(v string) *OutboxEventCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *OutboxEventCreate) SetPayload(v string) *OutboxEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillablePayload(v *string) *OutboxEventCreate {
	if v != nil {
		_c.SetPayload(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *OutboxEventCreate) SetAttempts(v int) *OutboxEventCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableAttempts(v *int) *OutboxEventCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_c *OutboxEventCreate) SetNextAttemptAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetNextAttemptAt(v)
	return _c
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableNextAttemptAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetNextAttemptAt(*v)
	}
	return _c
}

// SetLeaseUntil sets the "lease_until" field.
func (_c *OutboxEventCreate) SetLeaseUntil(v time.Time) *OutboxEventCreate {
	_c.mutation.SetLeaseUntil(v)
	return _c
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableLeaseUntil(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetLeaseUntil(*v)
	}
	return _c
}

// SetLeaseToken sets the "lease_token" field.
func (_c *OutboxEventCreate) SetLeaseToken(v string) *OutboxEventCreate {
	_c.mutation.SetLeaseToken(v)
	return _c
}

// SetNillableLeaseToken sets the "lease_token" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableLeaseToken(v *string) *OutboxEventCreate {
	if v != nil {
		_c.SetLeaseToken(*v)
	}
	return _c
}

// SetProcessedAt sets the "processed_at" field.
func (_c *OutboxEventCreate) SetProcessedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetProcessedAt(v)
	return _c
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableProcessedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetProcessedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *OutboxEventCreate) SetLastError(v string) *OutboxEventCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableLastError(v *string) *OutboxEventCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OutboxEventCreate) SetCreatedAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableCreatedAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OutboxEventCreate) SetID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableID(v *uuid.UUID) *OutboxEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_c *OutboxEventCreate) Mutation() *OutboxEventMutation {
	return _c.mutation
}

// Save creates the OutboxEvent in the database.
func (_c *OutboxEventCreate) Save(ctx context.Context) (*OutboxEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OutboxEventCreate) SaveX(ctx context.Context) *OutboxEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OutboxEventCreate) defaults() {
	if _, ok := _c.mutation.Payload(); !ok {
		v := outboxevent.DefaultPayload
		_c.mutation.SetPayload(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := outboxevent.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.NextAttemptAt(); !ok {
		v := outboxevent.DefaultNextAttemptAt()
		_c.mutation.SetNextAttemptAt(v)
	}
	if _, ok := _c.mutation.LeaseUntil(); !ok {
		v := outboxevent.DefaultLeaseUntil()
		_c.mutation.SetLeaseUntil(v)
	}
	if _, ok := _c.mutation.LeaseToken(); !ok {
		v := outboxevent.DefaultLeaseToken
		_c.mutation.SetLeaseToken(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := outboxevent.DefaultLastError
		_c.mutation.SetLastError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := outboxevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := outboxevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OutboxEventCreate) check() error {
	if _, ok := _c.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "OutboxEvent.operation_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "OutboxEvent.kind"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "OutboxEvent.payload"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "OutboxEvent.attempts"`)}
	}
	if _, ok := _c.mutation.NextAttemptAt(); !ok {
		return &ValidationError{Name: "next_attempt_at", err: errors.New(`ent: missing required field "OutboxEvent.next_attempt_at"`)}
	}
	if _, ok := _c.mutation.LeaseUntil(); !ok {
		return &ValidationError{Name: "lease_until", err: errors.New(`ent: missing required field "OutboxEvent.lease_until"`)}
	}
	if _, ok := _c.mutation.LeaseToken(); !ok {
		return &ValidationError{Name: "lease_token", err: errors.New(`ent: missing required field "OutboxEvent.lease_token"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "OutboxEvent.last_error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OutboxEvent.created_at"`)}
	}
	return nil
}

func (_c *OutboxEventCreate) sqlSave(ctx context.Context) (*OutboxEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OutboxEventCreate) createSpec() (*OutboxEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &OutboxEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(outboxevent.Table, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OperationID(); ok {
		_spec.SetField(outboxevent.FieldOperationID, field.TypeUUID, value)
		_node.OperationID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(outboxevent.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(outboxevent.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(outboxevent.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.NextAttemptAt(); ok {
		_spec.SetField(outboxevent.FieldNextAttemptAt, field.TypeTime, value)
		_node.NextAttemptAt = value
	}
	if value, ok := _c.mutation.LeaseUntil(); ok {
		_spec.SetField(outboxevent.FieldLeaseUntil, field.TypeTime, value)
		_node.LeaseUntil = value
	}
	if value, ok := _c.mutation.LeaseToken(); ok {
		_spec.SetField(outboxevent.FieldLeaseToken, field.TypeString, value)
		_node.LeaseToken = value
	}
	if value, ok := _c.mutation.ProcessedAt(); ok {
		_spec.SetField(outboxevent.FieldProcessedAt, field.TypeTime, value)
		_node.ProcessedAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(outboxevent.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(outboxevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OutboxEvent.Create().
//		SetOperationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OutboxEventUpsert) {
//			SetOperationID(v+v).
//		}).
//		Exec(ctx)
func (_c *OutboxEventCreate) OnConflict(opts ...sql.ConflictOption) *OutboxEventUpsertOne {
	_c.conflict = opts
	return &OutboxEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OutboxEventCreate) OnConflictColumns(columns ...string) *OutboxEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OutboxEventUpsertOne{
		create: _c,
	}
}

type (
	// OutboxEventUpsertOne is the builder for "upsert"-ing
	//  one OutboxEvent node.
	OutboxEventUpsertOne struct {
		create *OutboxEventCreate
	}

	// OutboxEventUpsert is the "OnConflict" setter.
	OutboxEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetOperationID sets the "operation_id" field.
func (u *OutboxEventUpsert) SetOperationID(v uuid.UUID) *OutboxEventUpsert {
	u.Set(outboxevent.FieldOperationID, v)
	return u
}

// UpdateOperationID sets the "operation_id" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateOperationID() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldOperationID)
	return u
}

// SetKind sets the "kind" field.
func (u *OutboxEventUpsert) SetKind(v string) *OutboxEventUpsert {
	u.Set(outboxevent.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateKind() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldKind)
	return u
}

// SetPayload sets the "payload" field.
func (u *OutboxEventUpsert) SetPayload(v string) *OutboxEventUpsert {
	u.Set(outboxevent.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdatePayload() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldPayload)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *OutboxEventUpsert) SetAttempts(v int) *OutboxEventUpsert {
	u.Set(outboxevent.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateAttempts() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *OutboxEventUpsert) AddAttempts(v int) *OutboxEventUpsert {
	u.Add(outboxevent.FieldAttempts, v)
	return u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *OutboxEventUpsert) SetNextAttemptAt(v time.Time) *OutboxEventUpsert {
	u.Set(outboxevent.FieldNextAttemptAt, v)
	return u
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateNextAttemptAt() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldNextAttemptAt)
	return u
}

// SetLeaseUntil sets the "lease_until" field.
func (u *OutboxEventUpsert) SetLeaseUntil(v time.Time) *OutboxEventUpsert {
	u.Set(outboxevent.FieldLeaseUntil, v)
	return u
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateLeaseUntil() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldLeaseUntil)
	return u
}

// SetLeaseToken sets the "lease_token" field.
func (u *OutboxEventUpsert) SetLeaseToken(v string) *OutboxEventUpsert {
	u.Set(outboxevent.FieldLeaseToken, v)
	return u
}

// UpdateLeaseToken sets the "lease_token" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateLeaseToken() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldLeaseToken)
	return u
}

// SetProcessedAt sets the "processed_at" field.
func (u *OutboxEventUpsert) SetProcessedAt(v time.Time) *OutboxEventUpsert {
	u.Set(outboxevent.FieldProcessedAt, v)
	return u
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateProcessedAt() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldProcessedAt)
	return u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *OutboxEventUpsert) ClearProcessedAt() *OutboxEventUpsert {
	u.SetNull(outboxevent.FieldProcessedAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *OutboxEventUpsert) SetLastError(v string) *OutboxEventUpsert {
	u.Set(outboxevent.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *OutboxEventUpsert) UpdateLastError() *OutboxEventUpsert {
	u.SetExcluded(outboxevent.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(outboxevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OutboxEventUpsertOne) UpdateNewValues() *OutboxEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(outboxevent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(outboxevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OutboxEventUpsertOne) Ignore() *OutboxEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OutboxEventUpsertOne) DoNothing() *OutboxEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OutboxEventCreate.OnConflict
// documentation for more info.
func (u *OutboxEventUpsertOne) Update(set func(*OutboxEventUpsert)) *OutboxEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OutboxEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperationID sets the "operation_id" field.
func (u *OutboxEventUpsertOne) SetOperationID(v uuid.UUID) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetOperationID(v)
	})
}

// UpdateOperationID sets the "operation_id" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateOperationID() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateOperationID()
	})
}

// SetKind sets the "kind" field.
func (u *OutboxEventUpsertOne) SetKind(v string) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateKind() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateKind()
	})
}

// SetPayload sets the "payload" field.
func (u *OutboxEventUpsertOne) SetPayload(v string) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdatePayload() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdatePayload()
	})
}

// SetAttempts sets the "attempts" field.
func (u *OutboxEventUpsertOne) SetAttempts(v int) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *OutboxEventUpsertOne) AddAttempts(v int) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateAttempts() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateAttempts()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *OutboxEventUpsertOne) SetNextAttemptAt(v time.Time) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateNextAttemptAt() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *OutboxEventUpsertOne) SetLeaseUntil(v time.Time) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateLeaseUntil() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateLeaseUntil()
	})
}

// SetLeaseToken sets the "lease_token" field.
func (u *OutboxEventUpsertOne) SetLeaseToken(v string) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetLeaseToken(v)
	})
}

// UpdateLeaseToken sets the "lease_token" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateLeaseToken() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateLeaseToken()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *OutboxEventUpsertOne) SetProcessedAt(v time.Time) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateProcessedAt() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *OutboxEventUpsertOne) ClearProcessedAt() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.ClearProcessedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *OutboxEventUpsertOne) SetLastError(v string) *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *OutboxEventUpsertOne) UpdateLastError() *OutboxEventUpsertOne {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *OutboxEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OutboxEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OutboxEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OutboxEventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OutboxEventUpsertOne.ID is not supported by MySQL driver. Use OutboxEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OutboxEventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OutboxEventCreateBulk is the builder for creating many OutboxEvent entities in bulk.
type OutboxEventCreateBulk struct {
	config
	err      error
	builders []*OutboxEventCreate
	conflict []sql.ConflictOption
}

// Save creates the OutboxEvent entities in the database.
func (_c *OutboxEventCreateBulk) Save(ctx context.Context) ([]*OutboxEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OutboxEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutboxEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OutboxEventCreateBulk) SaveX(ctx context.Context) []*OutboxEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OutboxEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OutboxEventUpsert) {
//			SetOperationID(v+v).
//		}).
//		Exec(ctx)
func (_c *OutboxEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *OutboxEventUpsertBulk {
	_c.conflict = opts
	return &OutboxEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OutboxEventCreateBulk) OnConflictColumns(columns ...string) *OutboxEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OutboxEventUpsertBulk{
		create: _c,
	}
}

// OutboxEventUpsertBulk is the builder for "upsert"-ing
// a bulk of OutboxEvent nodes.
type OutboxEventUpsertBulk struct {
	create *OutboxEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(outboxevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OutboxEventUpsertBulk) UpdateNewValues() *OutboxEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(outboxevent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(outboxevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OutboxEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OutboxEventUpsertBulk) Ignore() *OutboxEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OutboxEventUpsertBulk) DoNothing() *OutboxEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OutboxEventCreateBulk.OnConflict
// documentation for more info.
func (u *OutboxEventUpsertBulk) Update(set func(*OutboxEventUpsert)) *OutboxEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OutboxEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperationID sets the "operation_id" field.
func (u *OutboxEventUpsertBulk) SetOperationID(v uuid.UUID) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetOperationID(v)
	})
}

// UpdateOperationID sets the "operation_id" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateOperationID() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateOperationID()
	})
}

// SetKind sets the "kind" field.
func (u *OutboxEventUpsertBulk) SetKind(v string) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateKind() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateKind()
	})
}

// SetPayload sets the "payload" field.
func (u *OutboxEventUpsertBulk) SetPayload(v string) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdatePayload() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdatePayload()
	})
}

// SetAttempts sets the "attempts" field.
func (u *OutboxEventUpsertBulk) SetAttempts(v int) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *OutboxEventUpsertBulk) AddAttempts(v int) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateAttempts() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateAttempts()
	})
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (u *OutboxEventUpsertBulk) SetNextAttemptAt(v time.Time) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetNextAttemptAt(v)
	})
}

// UpdateNextAttemptAt sets the "next_attempt_at" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateNextAttemptAt() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateNextAttemptAt()
	})
}

// SetLeaseUntil sets the "lease_until" field.
func (u *OutboxEventUpsertBulk) SetLeaseUntil(v time.Time) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetLeaseUntil(v)
	})
}

// UpdateLeaseUntil sets the "lease_until" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateLeaseUntil() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateLeaseUntil()
	})
}

// SetLeaseToken sets the "lease_token" field.
func (u *OutboxEventUpsertBulk) SetLeaseToken(v string) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetLeaseToken(v)
	})
}

// UpdateLeaseToken sets the "lease_token" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateLeaseToken() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateLeaseToken()
	})
}

// SetProcessedAt sets the "processed_at" field.
func (u *OutboxEventUpsertBulk) SetProcessedAt(v time.Time) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetProcessedAt(v)
	})
}

// UpdateProcessedAt sets the "processed_at" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateProcessedAt() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateProcessedAt()
	})
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (u *OutboxEventUpsertBulk) ClearProcessedAt() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.ClearProcessedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *OutboxEventUpsertBulk) SetLastError(v string) *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *OutboxEventUpsertBulk) UpdateLastError() *OutboxEventUpsertBulk {
	return u.Update(func(s *OutboxEventUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *OutboxEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OutboxEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OutboxEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OutboxEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
