// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KHU-RETURN/rcp-server/ent/outboxevent"
	"github.com/KHU-RETURN/rcp-server/ent/predicate"
	"github.com/google/uuid"
)

// OutboxEventUpdate is the builder for updating OutboxEvent entities.
type OutboxEventUpdate struct {
	config
	hooks    []Hook
	mutation *OutboxEventMutation
}

// Where appends a list predicates to the OutboxEventUpdate builder.
func (_u *OutboxEventUpdate) Where(ps ...predicate.OutboxEvent) *OutboxEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOperationID sets the "operation_id" field.
func (_u *OutboxEventUpdate) SetOperationID(v uuid.UUID) *OutboxEventUpdate {
	_u.mutation.SetOperationID(v)
	return _u
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableOperationID(v *uuid.UUID) *OutboxEventUpdate {
	if v != nil {
		_u.SetOperationID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *OutboxEventUpdate) SetKind(v string) *OutboxEventUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableKind(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OutboxEventUpdate) SetPayload(v string) *OutboxEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillablePayload(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *OutboxEventUpdate) SetAttempts(v int) *OutboxEventUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableAttempts(v *int) *OutboxEventUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *OutboxEventUpdate) AddAttempts(v int) *OutboxEventUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *OutboxEventUpdate) SetNextAttemptAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableNextAttemptAt(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetLeaseUntil sets the "lease_until" field.
func (_u *OutboxEventUpdate) SetLeaseUntil(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetLeaseUntil(v)
	return _u
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableLeaseUntil(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetLeaseUntil(*v)
	}
	return _u
}

// SetLeaseToken sets the "lease_token" field.
func (_u *OutboxEventUpdate) SetLeaseToken(v string) *OutboxEventUpdate {
	_u.mutation.SetLeaseToken(v)
	return _u
}

// SetNillableLeaseToken sets the "lease_token" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableLeaseToken(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetLeaseToken(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *OutboxEventUpdate) SetProcessedAt(v time.Time) *OutboxEventUpdate {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableProcessedAt(v *time.Time) *OutboxEventUpdate {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *OutboxEventUpdate) ClearProcessedAt() *OutboxEventUpdate {
	_u.mutation.ClearProcessedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboxEventUpdate) SetLastError(v string) *OutboxEventUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OutboxEventUpdate) SetNillableLastError(v *string) *OutboxEventUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_u *OutboxEventUpdate) Mutation() *OutboxEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutboxEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutboxEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OutboxEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(outboxevent.Table, outboxevent.Columns, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperationID(); ok {
		_spec.SetField(outboxevent.FieldOperationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(outboxevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(outboxevent.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(outboxevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(outboxevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(outboxevent.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeaseUntil(); ok {
		_spec.SetField(outboxevent.FieldLeaseUntil, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeaseToken(); ok {
		_spec.SetField(outboxevent.FieldLeaseToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(outboxevent.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(outboxevent.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboxevent.FieldLastError, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutboxEventUpdateOne is the builder for updating a single OutboxEvent entity.
type OutboxEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboxEventMutation
}

// SetOperationID sets the "operation_id" field.
func (_u *OutboxEventUpdateOne) SetOperationID(v uuid.UUID) *OutboxEventUpdateOne {
	_u.mutation.SetOperationID(v)
	return _u
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableOperationID(v *uuid.UUID) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetOperationID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *OutboxEventUpdateOne) SetKind(v string) *OutboxEventUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableKind(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OutboxEventUpdateOne) SetPayload(v string) *OutboxEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillablePayload(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *OutboxEventUpdateOne) SetAttempts(v int) *OutboxEventUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableAttempts(v *int) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *OutboxEventUpdateOne) AddAttempts(v int) *OutboxEventUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *OutboxEventUpdateOne) SetNextAttemptAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableNextAttemptAt(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetLeaseUntil sets the "lease_until" field.
func (_u *OutboxEventUpdateOne) SetLeaseUntil(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetLeaseUntil(v)
	return _u
}

// SetNillableLeaseUntil sets the "lease_until" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableLeaseUntil(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetLeaseUntil(*v)
	}
	return _u
}

// SetLeaseToken sets the "lease_token" field.
func (_u *OutboxEventUpdateOne) SetLeaseToken(v string) *OutboxEventUpdateOne {
	_u.mutation.SetLeaseToken(v)
	return _u
}

// SetNillableLeaseToken sets the "lease_token" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableLeaseToken(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetLeaseToken(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *OutboxEventUpdateOne) SetProcessedAt(v time.Time) *OutboxEventUpdateOne {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableProcessedAt(v *time.Time) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *OutboxEventUpdateOne) ClearProcessedAt() *OutboxEventUpdateOne {
	_u.mutation.ClearProcessedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *OutboxEventUpdateOne) SetLastError(v string) *OutboxEventUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *OutboxEventUpdateOne) SetNillableLastError(v *string) *OutboxEventUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_u *OutboxEventUpdateOne) Mutation() *OutboxEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the OutboxEventUpdate builder.
func (_u *OutboxEventUpdateOne) Where(ps ...predicate.OutboxEvent) *OutboxEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutboxEventUpdateOne) Select(field string, fields ...string) *OutboxEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OutboxEvent entity.
func (_u *OutboxEventUpdateOne) Save(ctx context.Context) (*OutboxEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxEventUpdateOne) SaveX(ctx context.Context) *OutboxEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutboxEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OutboxEventUpdateOne) sqlSave(ctx context.Context) (_node *OutboxEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(outboxevent.Table, outboxevent.Columns, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OutboxEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outboxevent.FieldID)
		for _, f := range fields {
			if !outboxevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outboxevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperationID(); ok {
		_spec.SetField(outboxevent.FieldOperationID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(outboxevent.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(outboxevent.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(outboxevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(outboxevent.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(outboxevent.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeaseUntil(); ok {
		_spec.SetField(outboxevent.FieldLeaseUntil, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LeaseToken(); ok {
		_spec.SetField(outboxevent.FieldLeaseToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(outboxevent.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(outboxevent.FieldProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(outboxevent.FieldLastError, field.TypeString, value)
	}
	_node = &OutboxEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outboxevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
