// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KHU-RETURN/rcp-server/ent/resourceobservation"
	"github.com/google/uuid"
)

// ResourceObservationCreate is the builder for creating a ResourceObservation entity.
type ResourceObservationCreate struct {
	config
	mutation *ResourceObservationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetResourceKey sets the "resource_key" field.
func (_c *ResourceObservationCreate) SetResourceKey(v string) *ResourceObservationCreate {
	_c.mutation.SetResourceKey(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ResourceObservationCreate) SetKind(v string) *ResourceObservationCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetResourceID sets the "resource_id" field.
func (_c *ResourceObservationCreate) SetResourceID(v string) *ResourceObservationCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResourceObservationCreate) SetStatus(v string) *ResourceObservationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetConsistency sets the "consistency" field.
func (_c *ResourceObservationCreate) SetConsistency(v string) *ResourceObservationCreate {
	_c.mutation.SetConsistency(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *ResourceObservationCreate) SetReason(v string) *ResourceObservationCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *ResourceObservationCreate) SetNillableReason(v *string) *ResourceObservationCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *ResourceObservationCreate) SetObservedAt(v time.Time) *ResourceObservationCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_c *ResourceObservationCreate) SetNillableObservedAt(v *time.Time) *ResourceObservationCreate {
	if v != nil {
		_c.SetObservedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ResourceObservationCreate) SetID(v uuid.UUID) *ResourceObservationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ResourceObservationCreate) SetNillableID(v *uuid.UUID) *ResourceObservationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ResourceObservationMutation object of the builder.
func (_c *ResourceObservationCreate) Mutation() *ResourceObservationMutation {
	return _c.mutation
}

// Save creates the ResourceObservation in the database.
func (_c *ResourceObservationCreate) Save(ctx context.Context) (*ResourceObservation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceObservationCreate) SaveX(ctx context.Context) *ResourceObservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceObservationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceObservationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceObservationCreate) defaults() {
	if _, ok := _c.mutation.Reason(); !ok {
		v := resourceobservation.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		v := resourceobservation.DefaultObservedAt()
		_c.mutation.SetObservedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := resourceobservation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceObservationCreate) check() error {
	if _, ok := _c.mutation.ResourceKey(); !ok {
		return &ValidationError{Name: "resource_key", err: errors.New(`ent: missing required field "ResourceObservation.resource_key"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ResourceObservation.kind"`)}
	}
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "ResourceObservation.resource_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ResourceObservation.status"`)}
	}
	if _, ok := _c.mutation.Consistency(); !ok {
		return &ValidationError{Name: "consistency", err: errors.New(`ent: missing required field "ResourceObservation.consistency"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "ResourceObservation.reason"`)}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "ResourceObservation.observed_at"`)}
	}
	return nil
}

func (_c *ResourceObservationCreate) sqlSave(ctx context.Context) (*ResourceObservation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceObservationCreate) createSpec() (*ResourceObservation, *sqlgraph.CreateSpec) {
	var (
		_node = &ResourceObservation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resourceobservation.Table, sqlgraph.NewFieldSpec(resourceobservation.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ResourceKey(); ok {
		_spec.SetField(resourceobservation.FieldResourceKey, field.TypeString, value)
		_node.ResourceKey = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(resourceobservation.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(resourceobservation.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(resourceobservation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Consistency(); ok {
		_spec.SetField(resourceobservation.FieldConsistency, field.TypeString, value)
		_node.Consistency = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(resourceobservation.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(resourceobservation.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceObservation.Create().
//		SetResourceKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceObservationUpsert) {
//			SetResourceKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceObservationCreate) OnConflict(opts ...sql.ConflictOption) *ResourceObservationUpsertOne {
	_c.conflict = opts
	return &ResourceObservationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceObservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceObservationCreate) OnConflictColumns(columns ...string) *ResourceObservationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceObservationUpsertOne{
		create: _c,
	}
}

type (
	// ResourceObservationUpsertOne is the builder for "upsert"-ing
	//  one ResourceObservation node.
	ResourceObservationUpsertOne struct {
		create *ResourceObservationCreate
	}

	// ResourceObservationUpsert is the "OnConflict" setter.
	ResourceObservationUpsert struct {
		*sql.UpdateSet
	}
)

// SetResourceKey sets the "resource_key" field.
func (u *ResourceObservationUpsert) SetResourceKey(v string) *ResourceObservationUpsert {
	u.Set(resourceobservation.FieldResourceKey, v)
	return u
}

// UpdateResourceKey sets the "resource_key" field to the value that was provided on create.
func (u *ResourceObservationUpsert) UpdateResourceKey() *ResourceObservationUpsert {
	u.SetExcluded(resourceobservation.FieldResourceKey)
	return u
}

// SetKind sets the "kind" field.
func (u *ResourceObservationUpsert) SetKind(v string) *ResourceObservationUpsert {
	u.Set(resourceobservation.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ResourceObservationUpsert) UpdateKind() *ResourceObservationUpsert {
	u.SetExcluded(resourceobservation.FieldKind)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *ResourceObservationUpsert) SetResourceID(v string) *ResourceObservationUpsert {
	u.Set(resourceobservation.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ResourceObservationUpsert) UpdateResourceID() *ResourceObservationUpsert {
	u.SetExcluded(resourceobservation.FieldResourceID)
	return u
}

// SetStatus sets the "status" field.
func (u *ResourceObservationUpsert) SetStatus(v string) *ResourceObservationUpsert {
	u.Set(resourceobservation.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResourceObservationUpsert) UpdateStatus() *ResourceObservationUpsert {
	u.SetExcluded(resourceobservation.FieldStatus)
	return u
}

// SetConsistency sets the "consistency" field.
func (u *ResourceObservationUpsert) SetConsistency(v string) *ResourceObservationUpsert {
	u.Set(resourceobservation.FieldConsistency, v)
	return u
}

// UpdateConsistency sets the "consistency" field to the value that was provided on create.
func (u *ResourceObservationUpsert) UpdateConsistency() *ResourceObservationUpsert {
	u.SetExcluded(resourceobservation.FieldConsistency)
	return u
}

// SetReason sets the "reason" field.
func (u *ResourceObservationUpsert) SetReason(v string) *ResourceObservationUpsert {
	u.Set(resourceobservation.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *ResourceObservationUpsert) UpdateReason() *ResourceObservationUpsert {
	u.SetExcluded(resourceobservation.FieldReason)
	return u
}

// SetObservedAt sets the "observed_at" field.
func (u *ResourceObservationUpsert) SetObservedAt(v time.Time) *ResourceObservationUpsert {
	u.Set(resourceobservation.FieldObservedAt, v)
	return u
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *ResourceObservationUpsert) UpdateObservedAt() *ResourceObservationUpsert {
	u.SetExcluded(resourceobservation.FieldObservedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ResourceObservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resourceobservation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResourceObservationUpsertOne) UpdateNewValues() *ResourceObservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(resourceobservation.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceObservation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResourceObservationUpsertOne) Ignore() *ResourceObservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceObservationUpsertOne) DoNothing() *ResourceObservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceObservationCreate.OnConflict
// documentation for more info.
func (u *ResourceObservationUpsertOne) Update(set func(*ResourceObservationUpsert)) *ResourceObservationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceObservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetResourceKey sets the "resource_key" field.
func (u *ResourceObservationUpsertOne) SetResourceKey(v string) *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetResourceKey(v)
	})
}

// UpdateResourceKey sets the "resource_key" field to the value that was provided on create.
func (u *ResourceObservationUpsertOne) UpdateResourceKey() *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateResourceKey()
	})
}

// SetKind sets the "kind" field.
func (u *ResourceObservationUpsertOne) SetKind(v string) *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ResourceObservationUpsertOne) UpdateKind() *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateKind()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *ResourceObservationUpsertOne) SetResourceID(v string) *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ResourceObservationUpsertOne) UpdateResourceID() *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateResourceID()
	})
}

// SetStatus sets the "status" field.
func (u *ResourceObservationUpsertOne) SetStatus(v string) *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResourceObservationUpsertOne) UpdateStatus() *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateStatus()
	})
}

// SetConsistency sets the "consistency" field.
func (u *ResourceObservationUpsertOne) SetConsistency(v string) *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetConsistency(v)
	})
}

// UpdateConsistency sets the "consistency" field to the value that was provided on create.
func (u *ResourceObservationUpsertOne) UpdateConsistency() *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateConsistency()
	})
}

// SetReason sets the "reason" field.
func (u *ResourceObservationUpsertOne) SetReason(v string) *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *ResourceObservationUpsertOne) UpdateReason() *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateReason()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *ResourceObservationUpsertOne) SetObservedAt(v time.Time) *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *ResourceObservationUpsertOne) UpdateObservedAt() *ResourceObservationUpsertOne {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateObservedAt()
	})
}

// Exec executes the query.
func (u *ResourceObservationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceObservationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceObservationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResourceObservationUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ResourceObservationUpsertOne.ID is not supported by MySQL driver. Use ResourceObservationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResourceObservationUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResourceObservationCreateBulk is the builder for creating many ResourceObservation entities in bulk.
type ResourceObservationCreateBulk struct {
	config
	err      error
	builders []*ResourceObservationCreate
	conflict []sql.ConflictOption
}

// Save creates the ResourceObservation entities in the database.
func (_c *ResourceObservationCreateBulk) Save(ctx context.Context) ([]*ResourceObservation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResourceObservation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceObservationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceObservationCreateBulk) SaveX(ctx context.Context) []*ResourceObservation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceObservationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceObservationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceObservation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceObservationUpsert) {
//			SetResourceKey(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceObservationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResourceObservationUpsertBulk {
	_c.conflict = opts
	return &ResourceObservationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceObservation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceObservationCreateBulk) OnConflictColumns(columns ...string) *ResourceObservationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceObservationUpsertBulk{
		create: _c,
	}
}

// ResourceObservationUpsertBulk is the builder for "upsert"-ing
// a bulk of ResourceObservation nodes.
type ResourceObservationUpsertBulk struct {
	create *ResourceObservationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResourceObservation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resourceobservation.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResourceObservationUpsertBulk) UpdateNewValues() *ResourceObservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(resourceobservation.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceObservation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResourceObservationUpsertBulk) Ignore() *ResourceObservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceObservationUpsertBulk) DoNothing() *ResourceObservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceObservationCreateBulk.OnConflict
// documentation for more info.
func (u *ResourceObservationUpsertBulk) Update(set func(*ResourceObservationUpsert)) *ResourceObservationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceObservationUpsert{UpdateSet: update})
	}))
	return u
}

// SetResourceKey sets the "resource_key" field.
func (u *ResourceObservationUpsertBulk) SetResourceKey(v string) *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetResourceKey(v)
	})
}

// UpdateResourceKey sets the "resource_key" field to the value that was provided on create.
func (u *ResourceObservationUpsertBulk) UpdateResourceKey() *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateResourceKey()
	})
}

// SetKind sets the "kind" field.
func (u *ResourceObservationUpsertBulk) SetKind(v string) *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ResourceObservationUpsertBulk) UpdateKind() *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateKind()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *ResourceObservationUpsertBulk) SetResourceID(v string) *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *ResourceObservationUpsertBulk) UpdateResourceID() *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateResourceID()
	})
}

// SetStatus sets the "status" field.
func (u *ResourceObservationUpsertBulk) SetStatus(v string) *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ResourceObservationUpsertBulk) UpdateStatus() *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateStatus()
	})
}

// SetConsistency sets the "consistency" field.
func (u *ResourceObservationUpsertBulk) SetConsistency(v string) *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetConsistency(v)
	})
}

// UpdateConsistency sets the "consistency" field to the value that was provided on create.
func (u *ResourceObservationUpsertBulk) UpdateConsistency() *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateConsistency()
	})
}

// SetReason sets the "reason" field.
func (u *ResourceObservationUpsertBulk) SetReason(v string) *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *ResourceObservationUpsertBulk) UpdateReason() *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateReason()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *ResourceObservationUpsertBulk) SetObservedAt(v time.Time) *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *ResourceObservationUpsertBulk) UpdateObservedAt() *ResourceObservationUpsertBulk {
	return u.Update(func(s *ResourceObservationUpsert) {
		s.UpdateObservedAt()
	})
}

// Exec executes the query.
func (u *ResourceObservationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResourceObservationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceObservationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceObservationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
