// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/KHU-RETURN/rcp-server/ent/container"
	"github.com/KHU-RETURN/rcp-server/ent/instance"
	"github.com/KHU-RETURN/rcp-server/ent/keypair"
	"github.com/KHU-RETURN/rcp-server/ent/predicate"
	"github.com/KHU-RETURN/rcp-server/ent/user"
	"github.com/google/uuid"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGoogleID sets the "google_id" field.
func (_u *UserUpdate) SetGoogleID(v string) *UserUpdate {
	_u.mutation.SetGoogleID(v)
	return _u
}

// SetNillableGoogleID sets the "google_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGoogleID(v *string) *UserUpdate {
	if v != nil {
		_u.SetGoogleID(*v)
	}
	return _u
}

// SetGoogleAccessToken sets the "google_access_token" field.
func (_u *UserUpdate) SetGoogleAccessToken(v string) *UserUpdate {
	_u.mutation.SetGoogleAccessToken(v)
	return _u
}

// SetNillableGoogleAccessToken sets the "google_access_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGoogleAccessToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetGoogleAccessToken(*v)
	}
	return _u
}

// SetGoogleRefreshToken sets the "google_refresh_token" field.
func (_u *UserUpdate) SetGoogleRefreshToken(v string) *UserUpdate {
	_u.mutation.SetGoogleRefreshToken(v)
	return _u
}

// SetNillableGoogleRefreshToken sets the "google_refresh_token" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGoogleRefreshToken(v *string) *UserUpdate {
	if v != nil {
		_u.SetGoogleRefreshToken(*v)
	}
	return _u
}

// SetGoogleTokenExpiry sets the "google_token_expiry" field.
func (_u *UserUpdate) SetGoogleTokenExpiry(v time.Time) *UserUpdate {
	_u.mutation.SetGoogleTokenExpiry(v)
	return _u
}

// SetNillableGoogleTokenExpiry sets the "google_token_expiry" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGoogleTokenExpiry(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetGoogleTokenExpiry(*v)
	}
	return _u
}

// SetCurrentRefreshJti sets the "current_refresh_jti" field.
func (_u *UserUpdate) SetCurrentRefreshJti(v string) *UserUpdate {
	_u.mutation.SetCurrentRefreshJti(v)
	return _u
}

// SetNillableCurrentRefreshJti sets the "current_refresh_jti" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCurrentRefreshJti(v *string) *UserUpdate {
	if v != nil {
		_u.SetCurrentRefreshJti(*v)
	}
	return _u
}

// ClearCurrentRefreshJti clears the value of the "current_refresh_jti" field.
func (_u *UserUpdate) ClearCurrentRefreshJti() *UserUpdate {
	_u.mutation.ClearCurrentRefreshJti()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by IDs.
func (_u *UserUpdate) AddInstanceIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the Instance entity.
func (_u *UserUpdate) AddInstances(v ...*Instance) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// AddKeypairIDs adds the "keypairs" edge to the KeyPair entity by IDs.
func (_u *UserUpdate) AddKeypairIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddKeypairIDs(ids...)
	return _u
}

// AddKeypairs adds the "keypairs" edges to the KeyPair entity.
func (_u *UserUpdate) AddKeypairs(v ...*KeyPair) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddKeypairIDs(ids...)
}

// AddContainerIDs adds the "containers" edge to the Container entity by IDs.
func (_u *UserUpdate) AddContainerIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddContainerIDs(ids...)
	return _u
}

// AddContainers adds the "containers" edges to the Container entity.
func (_u *UserUpdate) AddContainers(v ...*Container) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContainerIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearInstances clears all "instances" edges to the Instance entity.
func (_u *UserUpdate) ClearInstances() *UserUpdate {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to Instance entities by IDs.
func (_u *UserUpdate) RemoveInstanceIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to Instance entities.
func (_u *UserUpdate) RemoveInstances(v ...*Instance) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// ClearKeypairs clears all "keypairs" edges to the KeyPair entity.
func (_u *UserUpdate) ClearKeypairs() *UserUpdate {
	_u.mutation.ClearKeypairs()
	return _u
}

// RemoveKeypairIDs removes the "keypairs" edge to KeyPair entities by IDs.
func (_u *UserUpdate) RemoveKeypairIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveKeypairIDs(ids...)
	return _u
}

// RemoveKeypairs removes "keypairs" edges to KeyPair entities.
func (_u *UserUpdate) RemoveKeypairs(v ...*KeyPair) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveKeypairIDs(ids...)
}

// ClearContainers clears all "containers" edges to the Container entity.
func (_u *UserUpdate) ClearContainers() *UserUpdate {
	_u.mutation.ClearContainers()
	return _u
}

// RemoveContainerIDs removes the "containers" edge to Container entities by IDs.
func (_u *UserUpdate) RemoveContainerIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveContainerIDs(ids...)
	return _u
}

// RemoveContainers removes "containers" edges to Container entities.
func (_u *UserUpdate) RemoveContainers(v ...*Container) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContainerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleID(); ok {
		_spec.SetField(user.FieldGoogleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleAccessToken(); ok {
		_spec.SetField(user.FieldGoogleAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleRefreshToken(); ok {
		_spec.SetField(user.FieldGoogleRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleTokenExpiry(); ok {
		_spec.SetField(user.FieldGoogleTokenExpiry, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentRefreshJti(); ok {
		_spec.SetField(user.FieldCurrentRefreshJti, field.TypeString, value)
	}
	if _u.mutation.CurrentRefreshJtiCleared() {
		_spec.ClearField(user.FieldCurrentRefreshJti, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KeypairsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.KeypairsTable,
			Columns: []string{user.KeypairsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keypair.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedKeypairsIDs(); len(nodes) > 0 && !_u.mutation.KeypairsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.KeypairsTable,
			Columns: []string{user.KeypairsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keypair.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeypairsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.KeypairsTable,
			Columns: []string{user.KeypairsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keypair.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContainersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ContainersTable,
			Columns: []string{user.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContainersIDs(); len(nodes) > 0 && !_u.mutation.ContainersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ContainersTable,
			Columns: []string{user.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContainersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ContainersTable,
			Columns: []string{user.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGoogleID sets the "google_id" field.
func (_u *UserUpdateOne) SetGoogleID(v string) *UserUpdateOne {
	_u.mutation.SetGoogleID(v)
	return _u
}

// SetNillableGoogleID sets the "google_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGoogleID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGoogleID(*v)
	}
	return _u
}

// SetGoogleAccessToken sets the "google_access_token" field.
func (_u *UserUpdateOne) SetGoogleAccessToken(v string) *UserUpdateOne {
	_u.mutation.SetGoogleAccessToken(v)
	return _u
}

// SetNillableGoogleAccessToken sets the "google_access_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGoogleAccessToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGoogleAccessToken(*v)
	}
	return _u
}

// SetGoogleRefreshToken sets the "google_refresh_token" field.
func (_u *UserUpdateOne) SetGoogleRefreshToken(v string) *UserUpdateOne {
	_u.mutation.SetGoogleRefreshToken(v)
	return _u
}

// SetNillableGoogleRefreshToken sets the "google_refresh_token" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGoogleRefreshToken(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGoogleRefreshToken(*v)
	}
	return _u
}

// SetGoogleTokenExpiry sets the "google_token_expiry" field.
func (_u *UserUpdateOne) SetGoogleTokenExpiry(v time.Time) *UserUpdateOne {
	_u.mutation.SetGoogleTokenExpiry(v)
	return _u
}

// SetNillableGoogleTokenExpiry sets the "google_token_expiry" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGoogleTokenExpiry(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetGoogleTokenExpiry(*v)
	}
	return _u
}

// SetCurrentRefreshJti sets the "current_refresh_jti" field.
func (_u *UserUpdateOne) SetCurrentRefreshJti(v string) *UserUpdateOne {
	_u.mutation.SetCurrentRefreshJti(v)
	return _u
}

// SetNillableCurrentRefreshJti sets the "current_refresh_jti" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCurrentRefreshJti(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetCurrentRefreshJti(*v)
	}
	return _u
}

// ClearCurrentRefreshJti clears the value of the "current_refresh_jti" field.
func (_u *UserUpdateOne) ClearCurrentRefreshJti() *UserUpdateOne {
	_u.mutation.ClearCurrentRefreshJti()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddInstanceIDs adds the "instances" edge to the Instance entity by IDs.
func (_u *UserUpdateOne) AddInstanceIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddInstanceIDs(ids...)
	return _u
}

// AddInstances adds the "instances" edges to the Instance entity.
func (_u *UserUpdateOne) AddInstances(v ...*Instance) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInstanceIDs(ids...)
}

// AddKeypairIDs adds the "keypairs" edge to the KeyPair entity by IDs.
func (_u *UserUpdateOne) AddKeypairIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddKeypairIDs(ids...)
	return _u
}

// AddKeypairs adds the "keypairs" edges to the KeyPair entity.
func (_u *UserUpdateOne) AddKeypairs(v ...*KeyPair) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddKeypairIDs(ids...)
}

// AddContainerIDs adds the "containers" edge to the Container entity by IDs.
func (_u *UserUpdateOne) AddContainerIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddContainerIDs(ids...)
	return _u
}

// AddContainers adds the "containers" edges to the Container entity.
func (_u *UserUpdateOne) AddContainers(v ...*Container) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContainerIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearInstances clears all "instances" edges to the Instance entity.
func (_u *UserUpdateOne) ClearInstances() *UserUpdateOne {
	_u.mutation.ClearInstances()
	return _u
}

// RemoveInstanceIDs removes the "instances" edge to Instance entities by IDs.
func (_u *UserUpdateOne) RemoveInstanceIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveInstanceIDs(ids...)
	return _u
}

// RemoveInstances removes "instances" edges to Instance entities.
func (_u *UserUpdateOne) RemoveInstances(v ...*Instance) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInstanceIDs(ids...)
}

// ClearKeypairs clears all "keypairs" edges to the KeyPair entity.
func (_u *UserUpdateOne) ClearKeypairs() *UserUpdateOne {
	_u.mutation.ClearKeypairs()
	return _u
}

// RemoveKeypairIDs removes the "keypairs" edge to KeyPair entities by IDs.
func (_u *UserUpdateOne) RemoveKeypairIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveKeypairIDs(ids...)
	return _u
}

// RemoveKeypairs removes "keypairs" edges to KeyPair entities.
func (_u *UserUpdateOne) RemoveKeypairs(v ...*KeyPair) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveKeypairIDs(ids...)
}

// ClearContainers clears all "containers" edges to the Container entity.
func (_u *UserUpdateOne) ClearContainers() *UserUpdateOne {
	_u.mutation.ClearContainers()
	return _u
}

// RemoveContainerIDs removes the "containers" edge to Container entities by IDs.
func (_u *UserUpdateOne) RemoveContainerIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveContainerIDs(ids...)
	return _u
}

// RemoveContainers removes "containers" edges to Container entities.
func (_u *UserUpdateOne) RemoveContainers(v ...*Container) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContainerIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleID(); ok {
		_spec.SetField(user.FieldGoogleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleAccessToken(); ok {
		_spec.SetField(user.FieldGoogleAccessToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleRefreshToken(); ok {
		_spec.SetField(user.FieldGoogleRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.GoogleTokenExpiry(); ok {
		_spec.SetField(user.FieldGoogleTokenExpiry, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CurrentRefreshJti(); ok {
		_spec.SetField(user.FieldCurrentRefreshJti, field.TypeString, value)
	}
	if _u.mutation.CurrentRefreshJtiCleared() {
		_spec.ClearField(user.FieldCurrentRefreshJti, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInstancesIDs(); len(nodes) > 0 && !_u.mutation.InstancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InstancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.InstancesTable,
			Columns: []string{user.InstancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(instance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.KeypairsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.KeypairsTable,
			Columns: []string{user.KeypairsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keypair.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedKeypairsIDs(); len(nodes) > 0 && !_u.mutation.KeypairsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.KeypairsTable,
			Columns: []string{user.KeypairsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keypair.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.KeypairsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.KeypairsTable,
			Columns: []string{user.KeypairsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(keypair.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContainersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ContainersTable,
			Columns: []string{user.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContainersIDs(); len(nodes) > 0 && !_u.mutation.ContainersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ContainersTable,
			Columns: []string{user.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContainersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ContainersTable,
			Columns: []string{user.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
