// Code generated by ent, DO NOT EDIT.

package keypair

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/KHU-RETURN/rcp-server/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLTE(FieldID, id))
}

// OpenstackName applies equality check predicate on the "openstack_name" field. It's identical to OpenstackNameEQ.
func OpenstackName(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldOpenstackName, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldFingerprint, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldPublicKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldUpdatedAt, v))
}

// OpenstackNameEQ applies the EQ predicate on the "openstack_name" field.
func OpenstackNameEQ(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldOpenstackName, v))
}

// OpenstackNameNEQ applies the NEQ predicate on the "openstack_name" field.
func OpenstackNameNEQ(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNEQ(FieldOpenstackName, v))
}

// OpenstackNameIn applies the In predicate on the "openstack_name" field.
func OpenstackNameIn(vs ...string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldIn(FieldOpenstackName, vs...))
}

// OpenstackNameNotIn applies the NotIn predicate on the "openstack_name" field.
func OpenstackNameNotIn(vs ...string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNotIn(FieldOpenstackName, vs...))
}

// OpenstackNameGT applies the GT predicate on the "openstack_name" field.
func OpenstackNameGT(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGT(FieldOpenstackName, v))
}

// OpenstackNameGTE applies the GTE predicate on the "openstack_name" field.
func OpenstackNameGTE(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGTE(FieldOpenstackName, v))
}

// OpenstackNameLT applies the LT predicate on the "openstack_name" field.
func OpenstackNameLT(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLT(FieldOpenstackName, v))
}

// OpenstackNameLTE applies the LTE predicate on the "openstack_name" field.
func OpenstackNameLTE(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLTE(FieldOpenstackName, v))
}

// OpenstackNameContains applies the Contains predicate on the "openstack_name" field.
func OpenstackNameContains(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldContains(FieldOpenstackName, v))
}

// OpenstackNameHasPrefix applies the HasPrefix predicate on the "openstack_name" field.
func OpenstackNameHasPrefix(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldHasPrefix(FieldOpenstackName, v))
}

// OpenstackNameHasSuffix applies the HasSuffix predicate on the "openstack_name" field.
func OpenstackNameHasSuffix(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldHasSuffix(FieldOpenstackName, v))
}

// OpenstackNameEqualFold applies the EqualFold predicate on the "openstack_name" field.
func OpenstackNameEqualFold(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEqualFold(FieldOpenstackName, v))
}

// OpenstackNameContainsFold applies the ContainsFold predicate on the "openstack_name" field.
func OpenstackNameContainsFold(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldContainsFold(FieldOpenstackName, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldContainsFold(FieldFingerprint, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "public_key" field.
func PublicKeyContains(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "public_key" field.
func PublicKeyHasPrefix(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "public_key" field.
func PublicKeyHasSuffix(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "public_key" field.
func PublicKeyEqualFold(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "public_key" field.
func PublicKeyContainsFold(v string) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldContainsFold(FieldPublicKey, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v SourceType) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v SourceType) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...SourceType) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...SourceType) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNotIn(FieldSourceType, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.KeyPair {
	return predicate.KeyPair(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.KeyPair {
	return predicate.KeyPair(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.KeyPair {
	return predicate.KeyPair(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasInstances applies the HasEdge predicate on the "instances" edge.
func HasInstances() predicate.KeyPair {
	return predicate.KeyPair(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InstancesTable, InstancesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstancesWith applies the HasEdge predicate on the "instances" edge with a given conditions (other predicates).
func HasInstancesWith(preds ...predicate.Instance) predicate.KeyPair {
	return predicate.KeyPair(func(s *sql.Selector) {
		step := newInstancesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.KeyPair) predicate.KeyPair {
	return predicate.KeyPair(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.KeyPair) predicate.KeyPair {
	return predicate.KeyPair(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.KeyPair) predicate.KeyPair {
	return predicate.KeyPair(sql.NotPredicates(p))
}
