// Code generated by ent, DO NOT EDIT.

package outboxevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/KHU-RETURN/rcp-server/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldID, id))
}

// OperationID applies equality check predicate on the "operation_id" field. It's identical to OperationIDEQ.
func OperationID(v uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldOperationID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldKind, v))
}

// Payload applies equality check predicate on the "payload" field. It's identical to PayloadEQ.
func Payload(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldPayload, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldAttempts, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldNextAttemptAt, v))
}

// LeaseUntil applies equality check predicate on the "lease_until" field. It's identical to LeaseUntilEQ.
func LeaseUntil(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldLeaseUntil, v))
}

// LeaseToken applies equality check predicate on the "lease_token" field. It's identical to LeaseTokenEQ.
func LeaseToken(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldLeaseToken, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldProcessedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldLastError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// OperationIDEQ applies the EQ predicate on the "operation_id" field.
func OperationIDEQ(v uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldOperationID, v))
}

// OperationIDNEQ applies the NEQ predicate on the "operation_id" field.
func OperationIDNEQ(v uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldOperationID, v))
}

// OperationIDIn applies the In predicate on the "operation_id" field.
func OperationIDIn(vs ...uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldOperationID, vs...))
}

// OperationIDNotIn applies the NotIn predicate on the "operation_id" field.
func OperationIDNotIn(vs ...uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldOperationID, vs...))
}

// OperationIDGT applies the GT predicate on the "operation_id" field.
func OperationIDGT(v uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldOperationID, v))
}

// OperationIDGTE applies the GTE predicate on the "operation_id" field.
func OperationIDGTE(v uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldOperationID, v))
}

// OperationIDLT applies the LT predicate on the "operation_id" field.
func OperationIDLT(v uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldOperationID, v))
}

// OperationIDLTE applies the LTE predicate on the "operation_id" field.
func OperationIDLTE(v uuid.UUID) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldOperationID, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldContainsFold(FieldKind, v))
}

// PayloadEQ applies the EQ predicate on the "payload" field.
func PayloadEQ(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldPayload, v))
}

// PayloadNEQ applies the NEQ predicate on the "payload" field.
func PayloadNEQ(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldPayload, v))
}

// PayloadIn applies the In predicate on the "payload" field.
func PayloadIn(vs ...string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldPayload, vs...))
}

// PayloadNotIn applies the NotIn predicate on the "payload" field.
func PayloadNotIn(vs ...string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldPayload, vs...))
}

// PayloadGT applies the GT predicate on the "payload" field.
func PayloadGT(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldPayload, v))
}

// PayloadGTE applies the GTE predicate on the "payload" field.
func PayloadGTE(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldPayload, v))
}

// PayloadLT applies the LT predicate on the "payload" field.
func PayloadLT(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldPayload, v))
}

// PayloadLTE applies the LTE predicate on the "payload" field.
func PayloadLTE(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldPayload, v))
}

// PayloadContains applies the Contains predicate on the "payload" field.
func PayloadContains(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldContains(FieldPayload, v))
}

// PayloadHasPrefix applies the HasPrefix predicate on the "payload" field.
func PayloadHasPrefix(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldHasPrefix(FieldPayload, v))
}

// PayloadHasSuffix applies the HasSuffix predicate on the "payload" field.
func PayloadHasSuffix(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldHasSuffix(FieldPayload, v))
}

// PayloadEqualFold applies the EqualFold predicate on the "payload" field.
func PayloadEqualFold(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEqualFold(FieldPayload, v))
}

// PayloadContainsFold applies the ContainsFold predicate on the "payload" field.
func PayloadContainsFold(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldContainsFold(FieldPayload, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldAttempts, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldNextAttemptAt, v))
}

// LeaseUntilEQ applies the EQ predicate on the "lease_until" field.
func LeaseUntilEQ(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldLeaseUntil, v))
}

// LeaseUntilNEQ applies the NEQ predicate on the "lease_until" field.
func LeaseUntilNEQ(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldLeaseUntil, v))
}

// LeaseUntilIn applies the In predicate on the "lease_until" field.
func LeaseUntilIn(vs ...time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldLeaseUntil, vs...))
}

// LeaseUntilNotIn applies the NotIn predicate on the "lease_until" field.
func LeaseUntilNotIn(vs ...time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldLeaseUntil, vs...))
}

// LeaseUntilGT applies the GT predicate on the "lease_until" field.
func LeaseUntilGT(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldLeaseUntil, v))
}

// LeaseUntilGTE applies the GTE predicate on the "lease_until" field.
func LeaseUntilGTE(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldLeaseUntil, v))
}

// LeaseUntilLT applies the LT predicate on the "lease_until" field.
func LeaseUntilLT(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldLeaseUntil, v))
}

// LeaseUntilLTE applies the LTE predicate on the "lease_until" field.
func LeaseUntilLTE(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldLeaseUntil, v))
}

// LeaseTokenEQ applies the EQ predicate on the "lease_token" field.
func LeaseTokenEQ(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldLeaseToken, v))
}

// LeaseTokenNEQ applies the NEQ predicate on the "lease_token" field.
func LeaseTokenNEQ(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldLeaseToken, v))
}

// LeaseTokenIn applies the In predicate on the "lease_token" field.
func LeaseTokenIn(vs ...string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldLeaseToken, vs...))
}

// LeaseTokenNotIn applies the NotIn predicate on the "lease_token" field.
func LeaseTokenNotIn(vs ...string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldLeaseToken, vs...))
}

// LeaseTokenGT applies the GT predicate on the "lease_token" field.
func LeaseTokenGT(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldLeaseToken, v))
}

// LeaseTokenGTE applies the GTE predicate on the "lease_token" field.
func LeaseTokenGTE(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldLeaseToken, v))
}

// LeaseTokenLT applies the LT predicate on the "lease_token" field.
func LeaseTokenLT(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldLeaseToken, v))
}

// LeaseTokenLTE applies the LTE predicate on the "lease_token" field.
func LeaseTokenLTE(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldLeaseToken, v))
}

// LeaseTokenContains applies the Contains predicate on the "lease_token" field.
func LeaseTokenContains(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldContains(FieldLeaseToken, v))
}

// LeaseTokenHasPrefix applies the HasPrefix predicate on the "lease_token" field.
func LeaseTokenHasPrefix(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldHasPrefix(FieldLeaseToken, v))
}

// LeaseTokenHasSuffix applies the HasSuffix predicate on the "lease_token" field.
func LeaseTokenHasSuffix(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldHasSuffix(FieldLeaseToken, v))
}

// LeaseTokenEqualFold applies the EqualFold predicate on the "lease_token" field.
func LeaseTokenEqualFold(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEqualFold(FieldLeaseToken, v))
}

// LeaseTokenContainsFold applies the ContainsFold predicate on the "lease_token" field.
func LeaseTokenContainsFold(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldContainsFold(FieldLeaseToken, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldProcessedAt, v))
}

// ProcessedAtIsNil applies the IsNil predicate on the "processed_at" field.
func ProcessedAtIsNil() predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIsNull(FieldProcessedAt))
}

// ProcessedAtNotNil applies the NotNil predicate on the "processed_at" field.
func ProcessedAtNotNil() predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotNull(FieldProcessedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldContainsFold(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OutboxEvent) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OutboxEvent) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OutboxEvent) predicate.OutboxEvent {
	return predicate.OutboxEvent(sql.NotPredicates(p))
}
