name: Go CD

on:
  push:
    branches: [ "main" ]  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        # 서버와 동일한 아키텍처(Linux)로 빌드합니다.
        run: GOOS=linux GOARCH=amd64 go build -v -o server ./cmd/api/main.go

      - name: Transfer Binary (SCP)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "server"
          target: "~/rcp-server/"

      - name: Restart Server (SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/rcp-server
            # 기존 프로세스 종료 (8080 포트)
            sudo fuser -k 8080/tcp || true
            # 새 서버 실행
            chmod +x server
            nohup ./server > app.log 2>&1 &
