// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// Container is the predicate function for container builders.
type Container func(*sql.Selector)

// Instance is the predicate function for instance builders.
type Instance func(*sql.Selector)

// KeyPair is the predicate function for keypair builders.
type KeyPair func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
